### ISSUE TITLE
Scratch account verification

### ISSUE THREAD

**Issue by andrewjcole** [OpenSprites/OpenSprites#100]
At the moment, I could create an account as Griffpatch and nobody would know if wasn't really him. We need some sort of verification in place.

**Comment by GrannyCookies** [comment]
Yeah, I'll be doing that now. Moar hacking of the EsoTalk source :P

**Comment by andrewjcole** [comment]
Why is this low priority????

**Comment by The-Cheese-Eater** [comment]
It is, but we don't have any users signing up anyway because people think the register system doesn't work yet. :P

**Comment by MegaApuTurkUltra** [comment]
We could have a bot account on scratch that has a verification project, and we use it to send hacked replies on that project where we fake the user ID so the user gets a message. Then, if the user replies to the hacked message, the bot can read that and verify the account.

**Comment by GrannyCookies** [comment]
wut

**Comment by The-Cheese-Eater** [comment]
We actually already have an account and verification project. ;)

**Comment by GrannyCookies** [comment]
I was just thinking of using the scratch comment api.

**Comment by GrannyCookies** [comment]
It'd be much easier xD

**Comment by MegaApuTurkUltra** [comment]
That's what I'm proposing. We can use the API to read comments, and we can also use it to send comments to the user to notify them (in case someone does try to impersonate). Something like:
> An account has been registered on OpenSprites under your name. Reply to this comment to verify that this is your account. If it is not your account, go to [http://opensprites.sampletext/del_account.php?id=(md5 of something here. Make it not easy to guess)](swag)

**Comment by bleush38p** [comment]
But then anyone could go on your page and if they saw your link, they could delete your account.

What about some sort of "post on this project if it isn't you" or (even better) "reply to this comment if it isn't you" system.
Or, you could go "reply to this comment in the next 30 minutes" or whatever to confirm your account.
*user opens scratch. replies to comment. tabs back to opensprites. opensprites hears onfocus and pings backend. backend goes yeah, okay! user is redirected to a yay!!1! page.*

**Comment by MegaApuTurkUltra** [comment]
Sounds good

**Comment by GrannyCookies** [comment]
Sounds good, now make it xD

**Comment by andrewjcole** [comment]
Don't look at me. XD

**Comment by bleush38p** [comment]
Feel free to look at me. I couldn't write php to save my life.

**Comment by Firedrake969** [comment]
Guys...
I wrote [this](https://github.com/OpenSprites/OpenSprites/blob/master/Site/register_old/register_check.php) a while ago...

Just implement it and fix it up (if it doesn't work - hasn't been tested, but should work)

**Comment by GrannyCookies** [comment]
@Firedrake969 Add it to the forums ;)

**Comment by Firedrake969** [comment]
Where would that be?

**Comment by GrannyCookies** [comment]
Use the ftp- I'll add it if you like. Does it work yet?

**Comment by Firedrake969** [comment]
I have the FTP credentials.

I meant where in the file system is the forum registration system?

**Comment by GrannyCookies** [comment]
/public_html/forums/core/controllers/ETUserController.class.php - line 127.

**Comment by GrannyCookies** [comment]
We need to get cheese to allow registering so we can test too

**Comment by The-Cheese-Eater** [comment]
I've allowed registering, but it will require an admin approval.

**Comment by GrannyCookies** [comment]
Ok
