### ISSUE TITLE
Registering

### ISSUE THREAD

**Issue by GrannyCookies** [OpenSprites/OpenSprites#101]
Does anybody have a backup of the EsoTalk file **_/forums/core/controllers/ETUserController.class.php_** from when @The-Cheese-Eater made the forums w/o my hax? I accidentally uploaded the x10.mx one which didn't work…

_Heh, Registering #101..._

**Comment by The-QullzToxic** [comment]
Cheese has a backup, allthough you'll have to wait until he gets off the car ferry xD

**Comment by The-QullzToxic** [comment]
Ooops

**Comment by GrannyCookies** [comment]
FIxed it.
