### ISSUE TITLE
Migrating to GitLab [IMPORTANT]

### ISSUE THREAD

**Issue by The-QullzToxic** [OpenSprites/OpenSprites#102]
I was thinking to migrate to GitLab due to free private repos, so we can keep part of our project private,  such as the forum.

**Comment by GrannyCookies** [comment]
The forum hax is fine, I've finished most of that.

**Comment by andrewjcole** [comment]
Is it much different? I'm happy with Github.

**Comment by GrannyCookies** [comment]
It's really nice. I've started migration- not sure if we should tho.

**Comment by GrannyCookies** [comment]
https://gitlab.com/OpenSprites/OpenSprites

**Comment by The-Cheese-Eater** [comment]
I like the idea of using GitLab, and I'm guessing everything will be cross-compatible and synced? At the moment I see no bonus of using GitLab over Hub just because of private repos. In any case, we are licensed under an MIT open source license so I'd like to keep things as public and transparent as possible.

**Comment by GrannyCookies** [comment]
@The-Cheese-Eater It's also a very nice interface in my opinion. Oh, and I added you as an owner on the GitLab group... https://gitlab.com/groups/OpenSprites/group_members

**Comment by The-Cheese-Eater** [comment]
Thanks. :)

**Comment by andrewjcole** [comment]
Uhh... do I need a new account?

**Comment by GrannyCookies** [comment]
No, login with your github one

**Comment by MegaApuTurkUltra** [comment]
I actually have time to contribute right now and everything is a mess! Let's please *not* move to gitlab. It's just super confusing.

**Comment by andrewjcole** [comment]
I open Github anyway. Having to open another tab will be a bother. I'm staying here until I need to leave.

**Comment by The-Cheese-Eater** [comment]
@GrannyCookies closed the GitLab now so back to how it was again. :)

**Comment by pilppe** [comment]
Then you should probably close this too
