### ISSUE TITLE
Non functioning EsoTalk top bar appears in login screen

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#103]
So far, the log in screen with forum integration is fantastic! :smile_cat: But for some reason a non-functioning top bar from the forums appears above the log in dialog. I expect this is a known bug. :P
![1](https://cloud.githubusercontent.com/assets/9347154/7106754/b2594bc4-e144-11e4-859a-9d7a4bbd5b98.png)

**Comment by GrannyCookies** [comment]
Um... it doesn't happen for me. Also, #102

**Comment by GrannyCookies** [comment]
What browser are you using?

**Comment by The-Cheese-Eater** [comment]
Waterfox (64 bit firefox basically)

**Comment by The-Cheese-Eater** [comment]
Lemme try with IE. ;P

**Comment by The-Cheese-Eater** [comment]
Works fine now, even in IE. :P

**Comment by GrannyCookies** [comment]
Hm... so is it fine now? XD

**Comment by GrannyCookies** [comment]
Also, do you like the seamless thingies? I do :P

**Comment by The-Cheese-Eater** [comment]
Yeah, it works great now. :D The EsoTalk integration is absolutely fantastic! I'm glad that we have you and EsoTalk as part of this project. :)

**Comment by GrannyCookies** [comment]
@The-Cheese-Eater Heh, I like modding the source code of software xD

**Comment by The-Cheese-Eater** [comment]
:P

**Comment by GrannyCookies** [comment]
=> Gitter?

**Comment by The-Cheese-Eater** [comment]
I can't at the moment. :(

**Comment by GrannyCookies** [comment]
Why?

**Comment by The-Cheese-Eater** [comment]
I joined just now but then realized everyone has gone to sleep. :rooster:
