### ISSUE TITLE
General Discussion

### ISSUE THREAD

**Issue by GrannyCookies** [OpenSprites/OpenSprites#104]
...

**Comment by GrannyCookies** [comment]
The resembelance is unreal:
![image](https://cloud.githubusercontent.com/assets/9429556/7106994/702f840e-e14c-11e4-94dd-333c8cb5bcab.png)

**Comment by GrannyCookies** [comment]
Just out of interest, who _uses the dark theme_? I do...

**Comment by andrewjcole** [comment]
I usually us the light theme. The color scheme is purdy.

**Comment by GrannyCookies** [comment]
Heh.

**Comment by The-Cheese-Eater** [comment]
Shouldn't the navigation bar change with the theme? It looks somewhat out of place in the dark theme.

**Comment by andrewjcole** [comment]
The login page should probably change too, somehow.

**Comment by MegaApuTurkUltra** [comment]
Let's not make general discussion an issue here. Use https://gitter.im/OpenSprites for discussion.

**Comment by GrannyCookies** [comment]
@andrewjcole You can change the forums theme on the forums, but once dev.opensprites merges into the main domain, they will be together
