### ISSUE TITLE
Can we not use text files for storage?

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [OpenSprites/OpenSprites#105]
MySQL is
 - More secure
 - Atomic
 - Easier to use
 - More swaggy
So why don't we use MySQL?

**Comment by The-Cheese-Eater** [comment]
I'm sure we already discussed this and chose MySQL. I don't know why somebody went with text files...

**Comment by GrannyCookies** [comment]
I chose text files, just because I'm not sure how to use MySQL xD

**Comment by andrewjcole** [comment]
Some things could use text files, but I'm pretty sure a database would be needed if we want to add a search.

**Comment by The-Cheese-Eater** [comment]
Perhaps things that don't need to have a fast and secure database could have a text file? It's certainly quicker and easier in the set up side of things. I'm not so restricted on Gwiddle with resources, but we need to be data efficient.

**Comment by MegaApuTurkUltra** [comment]
You're kidding right? Using text files for storage is one of those highly frowned upon things in programming...

**Comment by The-Cheese-Eater** [comment]
Ok, we'll use MySQL then. If you need a database creating you'll probably need to email me with your chosen credentials and info.

**Comment by MegaApuTurkUltra** [comment]
Sure thing. I'll also have to do stuff locally and on osdev.aputurk

**Comment by The-Cheese-Eater** [comment]
Righto.

**Comment by andrewjcole** [comment]
Let's say you're creating a card game with PHP. Would it make more sense to store the HTML in a txt or in a database? What if you only had like 6 cards?

**Comment by liam4** [comment]
Closed since we clearly have picked MySQL.
