### ISSUE TITLE
What do we use geobytes.com for?

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#106]
It appears in the list of domains a site requires in the µBlock menu.

**Comment by pilppe** [comment]
My guess would be tracking where people come from so we can have some kind of an understanding about the userbase.

**Comment by The-Cheese-Eater** [comment]
Ok. I'll have to add that to the Privacy Policy because some people get really touchy about geolocations because they think it pinpoints their exact location (very rare). :P

**Comment by pilppe** [comment]
You can tell them that Google tracks you almost all of the time. Might be a shock for them.

**Comment by The-Cheese-Eater** [comment]
I do try, but everyone I know believes that Google is the entire internet, so I may as well save my breath. :P

**Comment by GrannyCookies** [comment]
Reason is, it picks up if the user is located in the EU so it'll show to cookies policy.

**Comment by The-Cheese-Eater** [comment]
Ahh, ok. Is this data we use shared with Geobytes?

**Comment by GrannyCookies** [comment]
I don't understand :P
