### ISSUE TITLE
Not far to 1,337 commits!

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#107]
When the commit count ticks over to 1337, keep your changes local for a few hours so we can say weird things related to that number! :P

**Comment by pilppe** [comment]
Its not an issue though

**Comment by The-Cheese-Eater** [comment]
No, it's not an issue, but it's just a bit of fun. :P

**Comment by andrewjcole** [comment]
It's an issue if people don't leave it. :P

**Comment by The-Cheese-Eater** [comment]
Yo-ho-ho and a bottle of rum I read th' number wrong somehow. We actually have a pretty long way to be off. :P I'll close 'tis.

**Comment by andrewjcole** [comment]
For now.
oO
 •
