### ISSUE TITLE
Design resource pages

### ISSUE THREAD

**Issue by andrewjcole** [OpenSprites/OpenSprites#108]
~~Someone~~ I shall try to design some resource pages. 

https://github.com/OpenSprites/OpenSprites/blob/master/TODO.md

**Comment by The-Cheese-Eater** [comment]
If we will be hosting images for the forums, I don't think they will need a page. Shall we have every resource page the same or different designs for each?

**Comment by andrewjcole** [comment]
What exactly does "images for the forums" mean?

**Comment by The-Cheese-Eater** [comment]
It's been loosely suggested (by me) that we set up a system to host images to go on the Scratch forums. It would work like the normal media upload we have at the moment, but each picture has it's own short URL and doesn't have it's own page of place in the search database.

**Comment by andrewjcole** [comment]
What about sharing scripts?

**Comment by The-Cheese-Eater** [comment]
Yeah, we do want to do that as well so we can share custom blocks.

**Comment by andrewjcole** [comment]
Exactly, so wouldn't we need a page for that? Just use a template and load any details by using a querystring?

**Comment by The-Cheese-Eater** [comment]
Yeah. All it needs to be is a template, and we have content generated dynamically on the page.

**Comment by andrewjcole** [comment]
I guess I'll work on that a bit today.
