### ISSUE TITLE
Upload text font

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#109]
Could whoever made the images for the upload page say what the font below each picture is so we can use it under the WWW image?

**Comment by GrannyCookies** [comment]
http://www.dafont.com/new-super-mario-font-u.font

**Comment by The-Cheese-Eater** [comment]
Great, thanks! 
Can @MegaApuTurkUltra edit the URL upload image and change the font to the one above please?

**Comment by GrannyCookies** [comment]
@The-Cheese-Eater I've made new images for it that fit to theme, so it isn't needed now.

**Comment by The-Cheese-Eater** [comment]
Ok, thats better. :)

**Comment by MegaApuTurkUltra** [comment]
Maybe instead of using images, we should use webfonts and images only for the actual icons. It would make things like this easier to manage.

**Comment by GrannyCookies** [comment]
Maybe.

**Comment by andrewjcole** [comment]
If we ever did translations, it's easier to change text than text in an image.

**Comment by The-Cheese-Eater** [comment]
That's right.
