### ISSUE TITLE
Include login as a popover

### ISSUE THREAD

**Issue by andrewjcole** [OpenSprites/OpenSprites#110]
We should make it as we had it before, like Scratch does it. Here's the login form that can be included pretty much everywhere.

```html
<form action="http://opensprites.gwiddle.co.uk/forums/?p=user/login" method="post" enctype="multipart/form-data">
<input type="hidden" name="return" value="http://dev.opensprites.gwiddle.co.uk/">
<input type="hidden" name="token" value="2ad259bb23746">

<div class="sheetBody">


<div class="section">

<ul class="form">


<li><label>Username or Email</label> <div class="fieldGroup">

<input type="text" name="username" value="">
</div></li>


<li><label>Password <small><a href="/forums/?p=user/forgot" class="link-forgot" tabindex="-1">Forgot?</a></small></label> <div class="fieldGroup">

<input type="password" name="password" value="">
</div></li>


</ul>

</div>

</div>

<div class="buttons">
<input type="submit" name="login" value="Log In" class="big submit button">

</form>
```

**Comment by MegaApuTurkUltra** [comment]
I support this. @The-Cheese-Eater, is this OK to implement?

**Comment by The-Cheese-Eater** [comment]
It's ok as long as everything still fits in with EsoTalk.

**Comment by GrannyCookies** [comment]
Well, some styling will have to be required. But I support.

**Comment by andrewjcole** [comment]
I didn't bother including styling for this example. :P

**Comment by GrannyCookies** [comment]
I meant that we shouldn't use that form- we should use an iframe like /login/ as it EsoTalk won't let you log in _through other means_.

**Comment by andrewjcole** [comment]
Yep. :) The token seems to be the same all the time, so it's just a matter of copy, paste and adding styling. Even if we don't use a popover, we could replace the iframe with this so it doesn't look so ugly with the dark theme.

**Comment by GrannyCookies** [comment]
Heh, the forums will look fine once cheese merges dev.opensprites and opensprites. The localStorage doesn't carry over _os-theme_.

**Comment by The-Cheese-Eater** [comment]
I was thinking we should just screw the development sub-domain and move everything over to the main one? It's not like the main domain gets a high hit count, yet.

**Comment by GrannyCookies** [comment]
Yeah, maybe- it'll make my life easier :P

**Comment by GrannyCookies** [comment]
Have you seen my new [epic user pages](http://dev.opensprites.gwiddle.co.uk/users/4/)?

**Comment by The-Cheese-Eater** [comment]
Yeah, I have. :) But the background image on my profile looks a bit dodgy though. :P

**Comment by GrannyCookies** [comment]
I think it looks quite cool, to be honest :P

**Comment by GrannyCookies** [comment]
Try uploading some images- they appear on your profile page now! http://dev.opensprites.gwiddle.co.uk/users/4/

**Comment by GrannyCookies** [comment]
It automatically updates with ajax.

**Comment by The-Cheese-Eater** [comment]
Really cool! :D

**Comment by The-Cheese-Eater** [comment]
Though I'm not sure about the blurred logo as the background on my profile, and a big white box in the center. it doesn't contrast well, if thats what the arty people say. :P

**Comment by The-Cheese-Eater** [comment]
Oh, our first sound! http://dev.opensprites.gwiddle.co.uk/uploads/uploaded/1-4.mp3

**Comment by The-Cheese-Eater** [comment]
Did anyone implement this?

**Comment by The-Cheese-Eater** [comment]
Did anyone implement this? I can't remember is somebody mentioned if this was possible or not...

**Comment by GrannyCookies** [comment]
no

**Comment by andrewjcole** [comment]
I think the token field may change, unless it was just because of a forum reset.
