### ISSUE TITLE
Remove EsoTalk nav on forums and use sitewide nav?

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#111]
Would it be a good idea to do this and place the 'New Conversation' button under the new nav?

**Comment by GrannyCookies** [comment]
Yeah, is it EsoTalk hax time?

**Comment by andrewjcole** [comment]
Guess so. :3

**Comment by GrannyCookies** [comment]
Heh, I'll do it now- it's lunchtime @ school at the moment xP

**Comment by MegaApuTurkUltra** [comment]
I've taken a look at some of the code, I'm sure I could make the necessary changes.

**Comment by liam4** [comment]
Thing about this is that the messages button is gone on the forums. :P

**Comment by GrannyCookies** [comment]
@liam4 Not that it was pointless...
