### ISSUE TITLE
Carry over suspentions to main site

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#112]
At current, when a user in banned via EsoTalk, they are disallowed from posting on the forums. Also, the ban message tells the user to 'screw the moderator', which isn't really appropriate. :P

**Comment by The-Cheese-Eater** [comment]
This is high priority because there is no current way of stopping a user uploading stuff.

**Comment by GrannyCookies** [comment]
Will do.

**Comment by GrannyCookies** [comment]
I'll make an account, suspend it, then edit the message too.

**Comment by The-Cheese-Eater** [comment]
Ok, that is sorted then.
