### ISSUE TITLE
Bundle your commits!

### ISSUE THREAD

**Issue by pilppe** [OpenSprites/OpenSprites#113]
This is something, maybe not VERY important but people still seem to forget this.
In the busy weekends, when everyone is doing work EVERYONE should bundle. You can't imagine the pain of conflicts, just because (SORRY) @GrannyCookies keeps spamming commits because he doesnt bundle them.

I would love to see something done for this. 
Look at this:
![commits](https://cloud.githubusercontent.com/assets/8099538/7188592/95a07756-e481-11e4-9b74-d6f3e4165216.png)
Yes, it's awesome, but please.

**Comment by GrannyCookies** [comment]
I've started bundling them, but when there's a bug IN ONE FILE that I'd like to fix (without it having some irrelevant name) I'll just update it on GitHub. But I agree.

**Comment by GrannyCookies** [comment]
Also, when I work on chromebooks at school, I can't use Git and stuff so I CAN'T bundle my commits. So yeah.

**Comment by pilppe** [comment]
I'm not trying to be an arse, i understand. But you're not the only one who does this. For example @Rumanti did some php fixes that could have been done in 1 commit instead of 5 different commits.

**Comment by GrannyCookies** [comment]
Heh, okay. Have you seen the improved [user pages](http://dev.opensprites.gwiddle.co.uk/users/4/) yet?

**Comment by andrewjcole** [comment]
I think resource pages shouldn't look just like profile pages. It should have its own design.

**Comment by The-Cheese-Eater** [comment]
I agree with @andrewjcole on this one.

**Comment by andrewjcole** [comment]
I'd reccomend two columns, the right one bigger with a preview to the left and details to the right. Just an idea.

**Comment by Rumanti** [comment]
Sorry. I'll bundle next time.
