### ISSUE TITLE
Should uploads be "shareable"?

### ISSUE THREAD

**Issue by GrannyCookies** [OpenSprites/OpenSprites#114]
I'm going to implement "profile" pages for files soon, and I was wondering if we should have a sharing system in place for files. I don't think it's really needed, because the upload page will also allow you to set the title of the file etc before it is even uploaded to the server. So, should uploads be "shareable"?

**Comment by The-Cheese-Eater** [comment]
I don't think we need it really. If the user can define a title and description on upload then an extra 'sharing' page would make uploading less simple.

**Comment by GrannyCookies** [comment]
Yeah, I thought that too.

**Comment by GrannyCookies** [comment]
ugh, somebody has updated the main site to the "latest" commit whilsft I have a new one brewing up on my local computer. that's annoying

**Comment by MegaApuTurkUltra** [comment]
As long as you don't have file conflicts (which I actually have no idea how to resolve) it should be fine. Git pull doesn't overwrite your edited files

**Comment by The-Cheese-Eater** [comment]
Not me. @GrannyCookies
