### ISSUE TITLE
We need a mascot!

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#115]
Seriously, we need one. Having a mascot makes the site more personal to us. Whats-more, we can replace the default Scratch profile image with our own! Please can somebody really arty put themselves forward for this? It would be cool to have a vector version because we can use it for more things.

**Comment by MegaApuTurkUltra** [comment]
3tags5me

Hmm, lemme think about this

**Comment by andrewjcole** [comment]
I know! L'il plastic thing!

**Comment by MegaApuTurkUltra** [comment]
Haha, why didn't I think of that?

@pilppe would approve. @The-QullzToxic, maybe not :P

**Comment by The-Cheese-Eater** [comment]
That comment was funny and all, but still don't have a mascot. :P

**Comment by MegaApuTurkUltra** [comment]
How about a doge with mlg sunglasses and a dank snipar rifle?

**Comment by The-Cheese-Eater** [comment]
https://yt3.ggpht.com/-4O-B-UelDaI/AAAAAAAAAAI/AAAAAAAAAAA/H3q_jnHWKiU/s900-c-k-no/photo.jpg
?

**Comment by MegaApuTurkUltra** [comment]
@The-Cheese-Eater 7/8 not enough doritos

**Comment by The-Cheese-Eater** [comment]
http://i.cubeupload.com/pmPPo0.jpg

? :P

**Comment by MegaApuTurkUltra** [comment]
Awesome

**Comment by The-Cheese-Eater** [comment]
But seriously, it would be cool to have one. :P I'm surprised the arty people have not put themselves forward. :P

**Comment by andrewjcole** [comment]
I could take a stab at it whenever I can get on a computer.

**Comment by The-Cheese-Eater** [comment]
Please do! :D Could you try and make it cute, because that makes it more visually appealing to some people. I'm not sure everyone is a fan of all that MLG dog crisp drink gun malarkey. :P

**Comment by MegaApuTurkUltra** [comment]
> gun

\*dies\*
It's a **dank MLG snipar rifle**

**Comment by The-Cheese-Eater** [comment]
Well, if thats what it's called. :P I don't play those 'shoot 'em up' games. :P

**Comment by MegaApuTurkUltra** [comment]
> shoot em up

\*dies again\*
Do you not know what mlg montage parodies are?

**Comment by The-Cheese-Eater** [comment]
People have told me about MLG, but it's not something I think I'd watch on YouTube. :P

**Comment by MegaApuTurkUltra** [comment]
You totally should. They're hilarious :P

**Comment by The-Cheese-Eater** [comment]
I'll watch one tomorrow. :P

**Comment by The-Cheese-Eater** [comment]
Since I have not heard back from @andrewjcole over this, I'll see if I can find a Scratcher who can do this. I'm thinking about scratchifier?

**Comment by andrewjcole** [comment]
I don't have any ideas. Feel free to ask someone else until I can think of something genius.
