### ISSUE TITLE
Profile pages do not load while Scratch is down.

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#116]
Scratch it down atm, and the page just keeps churning away trying to load the profile images from Scratch. Should we keep a cached copy of all profile images?

**Comment by MegaApuTurkUltra** [comment]
Yes

**Comment by GrannyCookies** [comment]
Yes

**Comment by andrewjcole** [comment]
Yes

**Comment by pilppe** [comment]
Yes

**Comment by bleush38p** [comment]
Yes

**Comment by The-Cheese-Eater** [comment]
Well, that is decided then.

**Comment by GrannyCookies** [comment]
xD I'm not sure how we'd code it though. How would it work, if it fails to load the profile avatar load a cached copy?

**Comment by GrannyCookies** [comment]
We could just use the uploaded files used on the forums- then people like @pilppe won't have a weird profile image (pilppe isn't his scratch account *doh*)

**Comment by The-Cheese-Eater** [comment]
Yeah, but some people don't bother to upload images. :P

**Comment by jbayfield** [comment]
Also happens when the username on OpenSprites does not match an account on Scratch. For example, there is no jbayfield account on Scratch. (But I'm claiming it now while I still can)

**Comment by GrannyCookies** [comment]
@jbayfield Yeah, we need to edit site-api/user.php.
