### ISSUE TITLE
There are 14 stars, but 15 watchers?!

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [OpenSprites/OpenSprites#117]
Why have some people watched but not starred??

**Comment by bleush38p** [comment]
I'm *some people,* it would seem. OS is important to me in that I'm watching for updates, and all that, but for me (at this point at least) it's not something to star.

**Comment by The-Cheese-Eater** [comment]
I'm not quite sure what the start even means. :P Is it like a 'love-it' on Scratch? Once the site is up and running, we will get a lot more. ;)

**Comment by bleush38p** [comment]
To me, stars feel more like favorites, which, if you know me on scratch, you know I don't give out many of those.

**Comment by MegaApuTurkUltra** [comment]
It's like a love-it. I'm just curious why there are people who don't like OS but nevertheless want to watch it.
