### ISSUE TITLE
Who set up the opensprites.tk domain? & Development site hits 258.24 MB bandwidth usage!

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#118]
Somebody set up a .tk domain as a redirect not DNS. We are planning to buy a domain later on. :P
&
The development site has hit 258.24 MB bandwidth usage and the main domain getting 60 MB! At this point, I have now enabled Awstats to monitor search engines, referring domains and downloads. You guys are probably aware that Awstats isn't like Google analytics, and doesn't track keystrokes and what you click on. I cannot identify any info there directly to your username, so I'm not trying to stalk you. ;)

**Comment by The-Cheese-Eater** [comment]
Oh, and a few people are using the site on a Wii. :P

**Comment by MegaApuTurkUltra** [comment]
Use robots.txt to block baidu and yandex. They're evil

**Comment by GrannyCookies** [comment]
A wii? Wut?

**Comment by The-Cheese-Eater** [comment]
I know that Baidu is Chinese and Yandex is Russian, but don't we want to be indexed by them?

**Comment by GrannyCookies** [comment]
"They're evil"

**Comment by The-Cheese-Eater** [comment]
How though? :P

**Comment by GrannyCookies** [comment]
*shrugs* Oh, and you can delete uploads now.

**Comment by GrannyCookies** [comment]
And download them.

**Comment by The-Cheese-Eater** [comment]
Nice! :)

**Comment by MegaApuTurkUltra** [comment]
Baidu and yandex spammed djdolphin when he had a site, or something like that

**Comment by The-Cheese-Eater** [comment]
:/ I'll add it to the robots.txt then.

**Comment by andrewjcole** [comment]
I wonder if the Wii U user agent shows up as Wii, because I often browse with my Wii U.

**Comment by The-Cheese-Eater** [comment]
Probably. :P But why browse with a Wii U? I heard the normal Wii uses modded Opera?

**Comment by andrewjcole** [comment]
Touch screen, better HTML5 support, Gamepad only support...

**Comment by Rumanti** [comment]
Labels = "1337" and "illuminati" ???!! xD xD What the..?

**Comment by MegaApuTurkUltra** [comment]
@Rumanti yeah :P
