### ISSUE TITLE
Where is uploads/getHash.php ??

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [OpenSprites/OpenSprites#119]
I can't even get uploading to work!

The file_upload.php file has a function `InsertPairIntoFile`, what the heck is that? I thought we decided mysql?

Seriously, can I just rewrite file upload from scratch? Please?

**Comment by MegaApuTurkUltra** [comment]
Edit: Sorry, was confused by duplicate/old files. Can I delete them?

**Comment by GrannyCookies** [comment]
Yes
