### ISSUE TITLE
Content in sidebar?

### ISSUE THREAD

**Issue by andrewjcole** [OpenSprites/OpenSprites#12]
At the moment, we have some lorem opposem or whatever filling that space up. Any idea what we'll put there?

**Comment by The-Cheese-Eater** [comment]
I'm going to rip that sidebar out and replace it with something more useful. Or perhaps that could be the sign up box?

**Comment by andrewjcole** [comment]
Sign up could be done with a style-less form and inserted using a PHP include wherever needed. We could have a full sign up page or a sign up form on the main page that way. (I think out loud too much :P)

Your idea could work. Waiting for some more opinions.

**Comment by Firedrake969** [comment]
I vote remove it completely.

**Comment by The-Cheese-Eater** [comment]
I've ripped it out now then. It was kinda redundant.
