### ISSUE TITLE
Migrating to new image storage system

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [OpenSprites/OpenSprites#120]
Make sure to create a MySQL user/database on your local copy / the dev copy on gwiddle
```
Database: opensprites
User: opensprites
Password: swagmaster123
Global User Privileges: none
User Privileges on opensprites database: all (except maybe database drop)
```
Password is temporary, we obviously can't store it on this repo once OS goes into production

I have changed .htaccess, added /upload/_matu_upload.php, and added a button to switch to my uploading system on the upload page. I eventually want to make the entire thing AJAX-powered, kinda like PicturIt
Most of the code is copied from PicturIt, some ported to work here

**Comment by andrewjcole** [comment]
Ajax < Magic

**Comment by MegaApuTurkUltra** [comment]
What? Ajax &gt;&gt;  Magic! <sub><sup>(That's the mathematical &gt;&gt;, not the programming &gt;&gt;)</sup></sub>

**Comment by The-Cheese-Eater** [comment]
Can't I just email you the credentials @MegaApuTurkUltra? I can't use your ones because Gwiddle adds things to usernames. :P

**Comment by The-Cheese-Eater** [comment]
I've forwarded the details of the database to your aputurk email.

**Comment by GrannyCookies** [comment]
This is complete.
