### ISSUE TITLE
Admins need to be able to delete content.

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#122]
At the moment, I need to FTP into the site to moderate all content uploaded. Thankfully no bad content has been uploaded yet, but it would be good to have a page listing every upload and a image preview. I can then select select media to delete.

I'm also going to set registration to admin approval too, so we don't get anyone joining to try and mess up the system. I'll open it when I can moderate?

**Comment by andrewjcole** [comment]
I guess we need an admin.php or something, which probably can't stay open source.

**Comment by The-Cheese-Eater** [comment]
I don't think it will matter if it is open sourced or not because people will only be able to access it if logged in as me. :P The Scratch Team don't show images of their control panel, because it has top-secret ST stuff on it. :P All this one will have is a image preview a check box next to it and a big delete button at the top. :P

**Comment by andrewjcole** [comment]
Doesn't need to fancy. But it needs to be super secure. Will it have it's own password protected page, or will it integrate with admin accounts on the site?

**Comment by The-Cheese-Eater** [comment]
It should only be available to logged in mods and admins. I think we'll also password protect it for extra protection.

**Comment by GrannyCookies** [comment]
Well, deletion of files is secure still- you must be the logged in user. I'll allow admins to delete anything too

**Comment by andrewjcole** [comment]
So I guess it's up to one of the higher ups to work on this.

**Comment by jbayfield** [comment]
Assigned by cheeseeater

**Comment by jbayfield** [comment]
If you are in the Administrator/Moderator group on the forums, you can now delete content on it's 'profile' page.

**Comment by jbayfield** [comment]
Administrators can now delete/ban users. Closing as this task is now complete as of c2ceea5ccd
