### ISSUE TITLE
We already have forum image hosting capabilitys without need for more code

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#123]
All we need to add is a box with the direct image URL on the image's 'profile page'. No need for extra code or pages.

**Comment by GrannyCookies** [comment]
Where would this go, also what would the fallback be (e.g. no uploaded file)

**Comment by andrewjcole** [comment]
I think we should have a bit more than that, but make it a bit simpler, and less like the user pages.

**Comment by The-Cheese-Eater** [comment]
I think being able to share an image on the forum from it's own page is best so users don't get confused about what to upload to where?

**Comment by andrewjcole** [comment]
![my cool image](https://cloud.githubusercontent.com/assets/10202163/7215810/20dd37fa-e5bd-11e4-953c-f84e29c0f195.png)

**Comment by The-Cheese-Eater** [comment]
Yeah, me too, but with more styling. :P

**Comment by andrewjcole** [comment]
Hey, it was a 1 minute MS paint drawing. :P

**Comment by The-Cheese-Eater** [comment]
:3

**Comment by GrannyCookies** [comment]
Already works :P
