### ISSUE TITLE
Update me?

### ISSUE THREAD

**Issue by Firedrake969** [OpenSprites/OpenSprites#124]
Super busy, sorry, but I might have time again.  Could someone update me on what's going on and why are people spamming labels?  :P

**Comment by The-Cheese-Eater** [comment]
Basically, all the labels are @MegaApuTurkUltra's fault. :P jk 
MATU did add the comedy labels, and I like to use the Illuminati one on unexplained issues. :P 
In short: We've got the basic uploading system working, as well as registration, profiles and the forum.

**Comment by Firedrake969** [comment]
so we decided to use the forum reg system?  What about verification?

**Comment by The-Cheese-Eater** [comment]
I believe @GrannyCookies is going to incorporate verification into the EsoTalk sign-up.

**Comment by Firedrake969** [comment]
I can start, as I've already created a verification script (untested, but it's there!)

**Comment by andrewjcole** [comment]
Really? Is it uploaded yet?

**Comment by Firedrake969** [comment]
It's under registration_old

**Comment by GrannyCookies** [comment]
@Firedrake969 Welcome back :D
