### ISSUE TITLE
I am stuck logged in as "Guest" forever

### ISSUE THREAD

**Issue by andrewjcole** [OpenSprites/OpenSprites#125]
Nothing I do gets me out of this.

![stuck](https://cloud.githubusercontent.com/assets/10202163/7215844/a9fc48ea-e5be-11e4-807b-a24fb9ffbb3b.png)

<b>EDIT:</b> I can do it if do it through the forums. For some reason, before I logged in that way, it wouldn't let me log out of "guest"... if that makes any sense.

**Comment by Firedrake969** [comment]
Are we seriously using the forum system for a registration system?

**Comment by andrewjcole** [comment]
Umm... yep.

**Comment by Firedrake969** [comment]
...so what about Scratch-linked accounts?  (or verification)

**Comment by andrewjcole** [comment]
I've been nagging them to do something about it, but so far no progress on that. Only ideas have been discussed.

**Comment by Firedrake969** [comment]
I started something but someone deleted it

**Comment by Firedrake969** [comment]
https://github.com/OpenSprites/OpenSprites/tree/master/Site/register_old

**Comment by Firedrake969** [comment]
although it thinks that GrannyCookies made it :/

**Comment by andrewjcole** [comment]
Probably because he moved the files.

**Comment by Firedrake969** [comment]
Oh.  Should we start working on the 'real' registration system?

**Comment by andrewjcole** [comment]
I'm not sure. The team think that forums are the way to go right now. I don't really object, but it's kind of a pain that non-admins can't edit it.

**Comment by Firedrake969** [comment]
Why do they think that?

Seems like this is turning into private forums for us :P

**Comment by jbayfield** [comment]
What is the purpose of the Guest placeholder name? It just seems to be causing issues. I can push up an update but it means that the username won't be set to Guest

**Comment by andrewjcole** [comment]
@jbayfield I'm not sure. I think it's non-functional, as you can still log in through opensprites.gwiddle.co.uk/forums

**Comment by jbayfield** [comment]
Yeah, I'm looking at it, but it seems to serve no purpose. However the fix I had in mind seemed not to be working. I'll give it a shot to say the least.

**Comment by andrewjcole** [comment]
@Firedrake969 Have you seen profile pages yet? http://dev.opensprites.gwiddle.co.uk/users/5/

**Comment by Firedrake969** [comment]
I used to be able to see them...

**Comment by andrewjcole** [comment]
GrannyCookies and CheeseEater are gone right now. I'm not sure what's wrong with it.

**Comment by Firedrake969** [comment]
The user pages used to work... :/  I'll see if I can fix things

**Comment by jbayfield** [comment]
Found a bit of an issue, gonna try and sort that out. One sec.

**Comment by andrewjcole** [comment]
It does seem to do something. It prevents you from accessing the login page. It acts like you're logged in as "Guest", so it's not even just some useless HTML.

**Comment by The-Cheese-Eater** [comment]
I'm not quite sure who and why somebody made the guest thing because it's a problem. I think Granny Cookies is looking into putting Scratch verification into the EsoTalk sign-up.

**Comment by The-Cheese-Eater** [comment]
I'm having the guest issue too. We'll have to remove that

**Comment by jbayfield** [comment]
Fixed, pushing update now.

**Comment by andrewjcole** [comment]
What if we just leave it until GrannyCookies gets back? He's probably doing something. And we CAN

**Comment by andrewjcole** [comment]
Oops

**Comment by Firedrake969** [comment]
Just leave it open - I'll talk with GC to decide about registration

**Comment by jbayfield** [comment]
Addressed in 2d4a6dc - Fix in action at http://osdev.aputurk.tk/index.php

**Comment by jbayfield** [comment]
I'm assuming this can be considered closed now, GrannyCookies/other feel free to reopen if need be.
