### ISSUE TITLE
Dedicated Disk for OpenSprites

### ISSUE THREAD

**Issue by jbayfield** [OpenSprites/OpenSprites#126]
When OpenSprites goes into production I may be able to attach a dedicated storage disk to the host node, and then symlink a directory in the OpenSprites webspace to that drive.

It should in theory provide a better R/W speed as well as the benefit of isolating user data from the main node's disk.

Thoughts? Obviously code will need to be adjusted to write data to that specific "disk directory".

**Comment by The-Cheese-Eater** [comment]
That would certainly boost response time for the site! While at the moment, a solid site is more of a priority, speed will be once the site has users start uploading and downloading. When you say disk, I'm guessing you mean a virtual one on a physical SSD or HDD?

**Comment by jbayfield** [comment]
In this case it'd be a VHD attached to the Gwiddle Node, however the difference being is that the disk will be on an SSD-based storage node.

**Comment by The-Cheese-Eater** [comment]
Ok, that sounds great!

**Comment by jbayfield** [comment]
Ties in with #145. Changing milestone.
