### ISSUE TITLE
Possibility of having a dedicated OpenSprites Gwiddle account?

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#127]
At the moment, OpenSprites is hosted by my own Gwiddle account, but this means I can't give the credentials to other admins. Also, it makes it harder to track our data and disk usage since it adds on the stuff from my other websites too. This question is more directed at @jbayfield more than anyone else, but is there a possibility that we could transfer stuff from one account to another minimizing downtime and data loss? Also, is it a good idea trusting other admins with credentials to the main OpenSprites control panel? I know I can trust them, but passwords can fall into the wrong hands, and people can make mistakes and muck the entire site up...

**Comment by jbayfield** [comment]
The most critical thing to remember here is that whoever has access to the repository could also potentially ruin things, not just the site.

In terms of actually getting a shared account registered and migrating the files, that's easy.

If you are really concerned we can migrate the account, create a new domain in your account, symlink the shared directory to yours and then run backups on your account.
This way if anyone goes rogue they cannot tamper with the backup system.

**Comment by The-Cheese-Eater** [comment]
Yeah, you are right. I don't think the symlink will be needed though, because those with admin access shall only be: you, @Firedrake969, @GrannyCookies and myself. I've trusted Firedrake with the account on x10 before, and GrannyCookies with full FTP access. I think it would be better to have the entire account separated from mine, and treat the OpenSprites one like a new one. I know I'm being over cautious, but let me just clarify that doing with won't require a new domain and all our sub-domains will work as usual?

**Comment by jbayfield** [comment]
RE: Domains, yes, for the most part. It'll require a lot of manual work on my side but it's certainly possible.

**Comment by The-Cheese-Eater** [comment]
If you don't mind doing it, that would be great! Do you think it would be a better idea to get on with this now or schedule it for a few days/weeks/months?

**Comment by jbayfield** [comment]
I'm free tomorrow so it's something we can get done ASAP.

**Comment by The-Cheese-Eater** [comment]
Ok, that's good. I'm taking a break from my computer either in the morning or the afternoon to have a walk (most likely morning at about 9-10AM ish. GMT) But I'll be around most of the day.

**Comment by jbayfield** [comment]
Will be done today.

**Comment by GrannyCookies** [comment]
Is it still down?

**Comment by jbayfield** [comment]
Seems that the issue was not caused by the migration but rather dodgy code that we can't fix to save our lives.

No idea who was responsible but if you hold html_dom_parser against your name, fix it, because it's just causing everyone problems.

**Comment by GrannyCookies** [comment]
Uh... html_dom_parser is a php library...

**Comment by GrannyCookies** [comment]
Are you sure it was that? :P

**Comment by GrannyCookies** [comment]
I've fixed everything anyways now

**Comment by The-Cheese-Eater** [comment]
Phew, it was really tense on Gitter. :P We should look into ways of making sure that buggy code doesn't ruin the site. A separate branch where code is reviewed before being released to master? OSDev could fetch from the screening branch so we can see bugs in real time.
