### ISSUE TITLE
Something in .htaccess is preventing OpenSprites from running in a directory

### ISSUE THREAD

**Issue by jbayfield** [OpenSprites/OpenSprites#128]
Something is preventing relative paths from being parsed correctly when OpenSprites is being run from a directory.

Eg: where /assets/js/filename.js should direct to domain.com/**siteroot/**assets/js/filename.js, it instead redirects to domain.com**/**assets/js/filename.js

**Comment by The-Cheese-Eater** [comment]
Daww, c'mon firedrake. :P

**Comment by Firedrake969** [comment]
Things like that bug me :P

**Comment by The-Cheese-Eater** [comment]
We use the illuminati for odd problems :P

**Comment by Firedrake969** [comment]
Isn't anything that's broken "odd"?  xD

**Comment by jbayfield** [comment]
How's that?

**Comment by The-Cheese-Eater** [comment]
lol :P

**Comment by Firedrake969** [comment]
It's not in one of the last 4 rewrite rules, right?

**Comment by jbayfield** [comment]
I don't think so.

**Comment by Firedrake969** [comment]
lsat 5*

**Comment by Firedrake969** [comment]
Not sure but could be [this](https://github.com/OpenSprites/OpenSprites/blob/master/site-root/.htaccess#L33)

**Comment by jbayfield** [comment]
I'll tinker with it, see what happens

**Comment by Firedrake969** [comment]
Ok

**Comment by jbayfield** [comment]
Nope

**Comment by Firedrake969** [comment]
Only thing I can think of

**Comment by Firedrake969** [comment]
NO

**Comment by jbayfield** [comment]
Please keep issues serious, would appreciate any mucking around goes in OS/Chat.

**Comment by Firedrake969** [comment]
Only thing I can think of is adding each set of lines corresponding to one rule separately to see what happens.

**Comment by The-Cheese-Eater** [comment]
yeah, lets try and keep things serious. :P But let @MegaApuTurkUltra keep his labels. :P

**Comment by jbayfield** [comment]
It's puzzling as to why this is happening honestly, Rewrite shouldn't automatically bring it back to the root domain

**Comment by Firedrake969** [comment]
I'd rather not have arbitrary labels - just clutters things up.

Jokes and whatnot aside - have you tried what I thought about?

**Comment by jbayfield** [comment]
Yep. I've tried both RewriteBase and the extra rule.

**Comment by Firedrake969** [comment]
huh

**Comment by jbayfield** [comment]
Temporary workaround: Use vhosts to redirect to /Site

**Comment by jbayfield** [comment]
By design, OS is not written to operate within a directory. It must be located on a subdomain or domain.

**Comment by MegaApuTurkUltra** [comment]
@jbayfield So how can I get vhosts on osdev.aputurk? Or do I have to use my 2nd domain after all? Is it possible for gwiddle accounts to have more than 2 domains?
