### ISSUE TITLE
I just suspended myself.

### ISSUE THREAD

**Issue by GrannyCookies** [OpenSprites/OpenSprites#129]
HELP

**Comment by GrannyCookies** [comment]
PLEASE

**Comment by The-Cheese-Eater** [comment]
xD I've sorted it :P

**Comment by GrannyCookies** [comment]
Thanks

**Comment by GrannyCookies** [comment]
You made me a member, not a moderator :/

**Comment by The-Cheese-Eater** [comment]
Must have reset your group

**Comment by The-Cheese-Eater** [comment]
Done

**Comment by GrannyCookies** [comment]
Fixed now :)

**Comment by GrannyCookies** [comment]
I'm going to add some "ARE YOU SURE" stuff to those buttons o3o

**Comment by The-Cheese-Eater** [comment]
Good idea :P

**Comment by GrannyCookies** [comment]
Does the dev site load for you?

**Comment by GrannyCookies** [comment]
It has a ton of php errors for me

**Comment by GrannyCookies** [comment]
Fixed it.

**Comment by MegaApuTurkUltra** [comment]
Make users NOT able to suspend themselves, how about?

**Comment by The-Cheese-Eater** [comment]
I think only staff can suspend, so they should know better. :P

**Comment by GrannyCookies** [comment]
I'll add that anyway
