### ISSUE TITLE
Favicon.ico fails to open properly in GIMP.

### ISSUE THREAD

**Issue by DM5555** [OpenSprites/OpenSprites#13]
I am using GIMP 2.8.14 on Windows 8.
![failed logo](https://cloud.githubusercontent.com/assets/9368136/6068857/7e691b24-ad77-11e4-9380-aaf016068be2.png)

**Comment by The-Cheese-Eater** [comment]
Doesn't happen with my Windows 7 machine. Open it with office picture manager or firefox.

**Comment by 109C** [comment]
Fails to open with preview and is broken in gimp, mac 10.8

**Comment by DM5555** [comment]
Firefox is fine, GIMP is not

**Comment by DM5555** [comment]
What program was used to create the icon?

**Comment by The-Cheese-Eater** [comment]
I think cauzality used InkScape. Try that.

**Comment by The-Cheese-Eater** [comment]
I opened the file in GIMP and I got that weird effect. I think GIMP must be incompatible with .ico, but I don't know why...

**Comment by 109C** [comment]
I tested opening a test .ico in GIMP, and it works. Also 1.6 mb is quite a lot for a 16x16 pixel image, I think that *might* be related to why it can't open (unless it has 5000 frames)

**Comment by The-Cheese-Eater** [comment]
It's quite large in file size because it's has a large physical size. The browser resizes it and compresses it when it downloads it. I'll upload a smaller version anyhow.

**Comment by The-Cheese-Eater** [comment]
The compressed favicon now loads correctly in GIMP. Closing.
