### ISSUE TITLE
OpenSprites is not working correctly

### ISSUE THREAD

**Issue by jbayfield** [OpenSprites/OpenSprites#130]
This is due to a DDOS attack on Namecheap's DNS servers.
This is an issue outside of our control and no changes should be made to code to rectify it.

**Comment by GrannyCookies** [comment]
Um... isn't it?

**Comment by GrannyCookies** [comment]
It seems to be working fine (just a bit on the slow side)

**Comment by jbayfield** [comment]
The issue should now be resolved, but may return without warning.
