### ISSUE TITLE
WHO JUST RESET THE FORUMS!?

### ISSUE THREAD

**Issue by GrannyCookies** [OpenSprites/OpenSprites#131]
ARRRRRRRRRRRRRRRRRRRRRRRGH!!!!!

**Comment by The-Cheese-Eater** [comment]
No one, haven't you read the issue on migrating the Gwiddle users? :P

**Comment by GrannyCookies** [comment]
No, lol

**Comment by MegaApuTurkUltra** [comment]
Let's not spam in all caps please?
