### ISSUE TITLE
Deleted users don't return a 404 on their profile page, instead blank page

### ISSUE THREAD

**Issue by jbayfield** [OpenSprites/OpenSprites#134]
For example, http://dev.opensprites.gwiddle.co.uk/users/15/ links to a deleted user's profile, but instead of showing a 404 it shows the profile page with a lack of info.

**Comment by liam4** [comment]
Why closed? This is still something that needs to be fixed.

**Comment by GrannyCookies** [comment]
JIRA.

**Comment by The-Cheese-Eater** [comment]
Yeah, if there is an important issue that needs fixing, please bring it over to JIRA. :)

**Comment by liam4** [comment]
OH okay. Sorry! :P
