### ISSUE TITLE
Add support for uploading scripts; also verify audio files

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [OpenSprites/OpenSprites#135]
Just a placeholder so I remember to do this stuff.

A frontend GUI built off of scratchblocks2 for selecting scripts would be nice (I'll see what I can do).

**Comment by andrewjcole** [comment]
For sprite2 files, someone should make a browser so they can see what's in it before downloading on the download page.

**Comment by MegaApuTurkUltra** [comment]
@andrewjcole on the upload page I've used jszip to extract assets locally and upload them separately,  because of the way asset storage works (we don't want duplicate assets so my script checks the md5s). I'm thinking we can have asset groups or sets or something, especially useful if you need multiple scripts in a thing (custom blocks, etc)
