### ISSUE TITLE
Domain name & SSL

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#136]
My birthday is coming up next month, so this opens up a window of opportunity to grab ourselves a domain... unless anyone else wants to buy it. ;) I just want to ask, are we 100% serious that we want to do this and are we sure that we won't let this project flop.

Is it worth enabling SSL too? It's almost standard to have an encrypted service for sites with logins these days. SSL certs do cost money though and SSL can break things.

**Comment by The-Cheese-Eater** [comment]
MATU has a valid point here "Let's wait on a domain and ssl Until we're actually production ready"
It's just I won't have another chance to get this without paying with my own money (limited). :P

**Comment by jbayfield** [comment]
If you are going to do this, please do it with Namecheap and get the SSL when you buy the domain, it's much cheaper. I can always install it for you later.

**Comment by The-Cheese-Eater** [comment]
Ok, I'm planning on using NameCheap when the time comes around anyhow. ;)

**Comment by GrannyCookies** [comment]
Hm... maybe reserve the domain, if you can. Also, ssl might break things (e.g. http/s don't match)

**Comment by MegaApuTurkUltra** [comment]
To prevent breaking things, make sure to use `//sample.text/script.js` when loading external assets instead of `http://` or `https://` - just `//` will make sure it uses the same protocol.
