### ISSUE TITLE
Reverted to eceeef176448ee348e1461ac64bc9f6cfbcdf404

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [OpenSprites/OpenSprites#139]
I needed to restore the upload scripts that were overwritten. Also, it seems quillz did break something. This commit was my last one yesterday, right before the one from quillz.  
Commit: https://github.com/OpenSprites/OpenSprites/commit/eceeef176448ee348e1461ac64bc9f6cfbcdf404

If anyone has code they need back that I may have deleted, comment here and I can get it off of dev.opensprites before another update. I was stupid and didn't realize a hard reset would actually remove those commits, and I did not have a chance to look at the code (sorry!)

<sub><sup>Also do you like my brand new "short term" label?</sup></sub>

**Comment by The-Cheese-Eater** [comment]
Snazzy new label. :P

**Comment by The-QullzToxic** [comment]
Forget my code, I'm an idiot for not checking what I was pushing

All I did was

git pull
git commit -m Blog GUI updates.
git push 

exactly as it told me.

**Comment by MegaApuTurkUltra** [comment]
Resolved
