### ISSUE TITLE
Database Columns

### ISSUE THREAD

**Issue by Firedrake969** [OpenSprites/OpenSprites#14]
Columns so far:

username
password (hashed, of course!)
email
user_key (for logins)
date (date registered)

Thoughts on these ones?
IP
rank

**Comment by The-Cheese-Eater** [comment]
We indefinitely need to store IPs in case of bans, etc. We'd also need to store ranks. The only three ranks we will have are: Admin, uploaded media screener (UMS), and Scratcher. Possibly browser/OS information for statistics and to help stop ban evading?

**Comment by Firedrake969** [comment]
Done for the first two.  IP will have to be updated every time you log in, and browser/OS info is really finicky.

**Comment by The-Cheese-Eater** [comment]
Ok, well lets leave OS stuff for later on. I don't want to write long privacy policies on data collection just yet...

**Comment by Firedrake969** [comment]
Yeah... xD

Though we will use cookies, so we might want to say that.

**Comment by MegaApuTurkUltra** [comment]
Right, so we're going to need a privacy policy. (a document that explains
all the forms of storage we use for our data, what data we collect, and why
we collect it). Something like

"To store information about account authentication, we use 'cookies.'
Cookies are short pieces of text which are stored on a user's computer by
their browser. Cookies make sure we can store a user's logged-in state
between page navigations."

and continue for account info storage in a database, ips, browser info, etc.

**Comment by Firedrake969** [comment]
https://github.com/OpenSprites/OpenSprites/issues/15 to discuss the privacy policy

**Comment by The-Cheese-Eater** [comment]
I'll do it, unless anyone else is good with policies.
