### ISSUE TITLE
Have a script editor on-site?

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [OpenSprites/OpenSprites#142]
I was thinking (here: https://github.com/OpenSprites/OpenSprites/issues/140#issuecomment-94586906) that instead of wasting space by allowing users to upload entire sprite files, we make "sprites" be virtual collections of assets that can be downloaded in one bundle. This has the pros of using less server space (no duplicate assets), and allowing everyone who contributed assets to a collection to receive credit.

However this raises the problem: what if someone wants to turn several peoples' assets (and scripts) into a collection, and it doesn't *quite* work out (minor edits to scripts needed, perhaps)?

I think this would require a mini on-site script editor, to sort small issues in scripts out. Maybe we could use pixie?

Thoughts?

**Comment by andrewjcole** [comment]
Never thought of something like this. It would probably be best for editing, because uploading a script without testing makes no sense. :P

**Comment by MegaApuTurkUltra** [comment]
I just realized, if we make this, we might as well add an image and sound editor as well... Might be complicated :P

**Comment by liam4** [comment]
I totally vote up on this.

**Comment by andrewjcole** [comment]
I wonder if there are any open source sound editors out there? As for image editors, vector stuff would be kind of hard, unless you converted it to PNG and put it on an HTML5 canvas.

**Comment by liam4** [comment]
Why you close everything @The-Cheese-Eater ;-;

This still needs to be worked on!

**Comment by The-Cheese-Eater** [comment]
See my other comment. ;)

**Comment by liam4** [comment]
Ahh okay. Sorry, didn't see it

–––
Actually it wasn't there when I posted that.. :P
