### ISSUE TITLE
Can I help?

### ISSUE THREAD

**Issue by easyscratcher** [OpenSprites/OpenSprites#143]
Hello! I love to code! Maybe I can help?

**Comment by MegaApuTurkUltra** [comment]
Are you on Scratch?

We'd be glad to have an additional member.

What programming and markup languages do you know?

**Comment by GrannyCookies** [comment]
@MegaApuTurkUltra He helped make ScratchExt 2.0. Easy'd be good for html/js.

**Comment by jbayfield** [comment]
Seems kay. @The-Cheese-Eater, input please.

**Comment by The-Cheese-Eater** [comment]
Sure! Just so we can see what you'd like to add to the site, could you clone our repository, add your changes, and if we like it, we'll make a pull request. :) Then I'll add you as a organization member.

**Comment by easyscratcher** [comment]
@The-Cheese-Eater Yay :D

**Comment by GrannyCookies** [comment]
@easyscratcher [Join OpenSprites](http://dev.opensprites.gwiddle.co.uk/register/), too :P

**Comment by easyscratcher** [comment]
@GrannyCookies The Verify Scratch account isn't working.

**Comment by easyscratcher** [comment]
@all And I can translate OpenSprites to german, too ;D

**Comment by GrannyCookies** [comment]
Isn't it?

**Comment by The-Cheese-Eater** [comment]
That would be pretty cool! :D I've alerted to GrannyCookies to the problem

**Comment by easyscratcher** [comment]
great

**Comment by The-Cheese-Eater** [comment]
Could you give us more info? Error?

**Comment by GrannyCookies** [comment]
Yeah ^

**Comment by GrannyCookies** [comment]
I just made the system.

**Comment by easyscratcher** [comment]
![2015-04-22 19_15_51-sign up - opensprites forum](https://cloud.githubusercontent.com/assets/10178784/7280595/1b26069c-e924-11e4-8fa6-d757320693d0.png)

**Comment by GrannyCookies** [comment]
That's all you can say really, isn't it :P

**Comment by GrannyCookies** [comment]
Let me add debug stuff

**Comment by GrannyCookies** [comment]
done

**Comment by GrannyCookies** [comment]
what's the error now?

**Comment by easyscratcher** [comment]
![2015-04-22 19_23_28-sign up - opensprites forum](https://cloud.githubusercontent.com/assets/10178784/7280733/27c12cd2-e925-11e4-8fcf-1459de0d495f.png)

**Comment by GrannyCookies** [comment]
Try now

**Comment by easyscratcher** [comment]
kay

**Comment by easyscratcher** [comment]
It works :D

**Comment by The-Cheese-Eater** [comment]
Great! :)
