### ISSUE TITLE
Migrate to Atlassian JIRA

### ISSUE THREAD

**Issue by jbayfield** [OpenSprites/OpenSprites#144]
Title says it all, really.

**Comment by jbayfield** [comment]
Done.
https://opensprites.atlassian.net

**Comment by liam4** [comment]
I should sign up now..

**Comment by andrewjcole** [comment]
It's more complicated than it needs to be. I don't get why we need the issues so private anyway.

**Comment by The-Cheese-Eater** [comment]
Private issues are just the way that JIRA works, we don't set it up like that. You get used to working on it after a while, just give it a chance. :)

**Comment by andrewjcole** [comment]
Other than that, what does it add that Github can't do?

**Comment by GrannyCookies** [comment]
@andrewjcole swag
