### ISSUE TITLE
ISSUE TRACKER HAS MOVED TO JIRA

### ISSUE THREAD

**Issue by jbayfield** [OpenSprites/OpenSprites#146]
https://opensprites.atlassian.net/secure/Dashboard.jspa

Every registered OpenSprites Developer has been sent an email to create a password for their new account. For a quick guide on how to use JIRA and what it is, see this: http://dev.opensprites.gwiddle.co.uk/JIRATutorial.wmv

**Comment by GrannyCookies** [comment]
You're done?

**Comment by MegaApuTurkUltra** [comment]
Awesome

**Comment by The-Cheese-Eater** [comment]
Remember to watch this: http://dev.opensprites.gwiddle.co.uk/JIRATutorial.wmv

**Comment by andrewjcole** [comment]
Aww... man I have to download it. :P

**Comment by The-Cheese-Eater** [comment]
Don't worry, zeus isn't going to pop up on your screen and shout "trooooooll!". :P

**Comment by andrewjcole** [comment]
I'll have to watch when I get home because I have to go to school in 1.23 minutes.

**Comment by andrewjcole** [comment]
What's with all the strange tags these days, anyway?

**Comment by MegaApuTurkUltra** [comment]
haha lolz
