### ISSUE TITLE
Notifications in JIRA/Confluence

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#147]
I know this is a GitHub issue, but seeing as some people are not using JIRA yet, I'll put this here.

If you like the notification system on GitHub to see comments posted on issues, there is a way of doing this in JIRA/Confluence. Log into your account [here](http://opensprites.atlassian.net/), once logged in, hit the Hamburger icon and select 'Confluence' from the drop-down menu. You will now see the notification tray similar to GitHub's appear next to your user icon. By clicking one of the modified issues displayed, you will see recent comments and changes to that issue, like GitHub.

**List of modified issues:**
![image](https://cloud.githubusercontent.com/assets/9347154/7328267/f8680052-eacb-11e4-9fd7-b9342c7440db.png)

**Recent changes to an issue:**
![image](https://cloud.githubusercontent.com/assets/9347154/7328282/1df63d2a-eacc-11e4-8ca1-1fd2064cc96b.png)

Please excuse the full-page screen shots, I've not got around to installing basic image manipulating software yet. :P

**Comment by andrewjcole** [comment]
<offtopic>Which OS is that? Is that Windows 2000 or a style for Windows 7?</offtopic>

**Comment by The-Cheese-Eater** [comment]
Nah it's Windows XP. :P I use this old PC with 1.24GB of RAM and an Pentium 4 I clocked at 3.04 Ghz. Apart from the RAM, it's actually faster than my Windows 7 laptop because it doesn't have so much rubbish installed and I'm not using a fancy theme (and the clock speed is faster). :P This is actually turning into my main PC, for OpenSprites, anyhow; I have a HDD dedicated to daily backups. :P

**Comment by andrewjcole** [comment]
Ah, OK. I use Windows XP for my old laptop that I'm using right now because it seems to work a lot better than Ubuntu, Windows Vista/7 and Linux Mint. It was either XP or 2000, which also worked well too, soo... :P

**Comment by The-Cheese-Eater** [comment]
:P

**Comment by The-Cheese-Eater** [comment]
Test comment

**Comment by MegaApuTurkUltra** [comment]
Testing 123

**Comment by andrewjcole** [comment]
Why are we test commenting?

**Comment by GrannyCookies** [comment]
test lel

**Comment by The-Cheese-Eater** [comment]
To test the Gitter integration :P

**Comment by Rumanti** [comment]
I just watched the tutorial video today, (I had been busy and I just came back from my mini weekend computer-less vacation) and I feel this is a silly question but how do you contact Zeusking19 to request an account? Here? https://opensprites.atlassian.net/admin/users/sign-up ( I just did this )

**Comment by The-Cheese-Eater** [comment]
I'll take a look for you. :)

**Comment by Rumanti** [comment]
Well, I think it's correct. I got the email, logged in, and see the developer agreement (which only logged in users can see.. right?)

**Comment by The-Cheese-Eater** [comment]
Yep! Click the hamburger icon in the corner to navigate to JIRA, our new issues platform.
