### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by pilppe** [OpenSprites/OpenSprites#148]
How cool would be a site translated to your own language?
Imagine OpenSprites in Hebrew? If your native language is Hebrew, why not translate it to your own language? Well its not possible right now.

We should create a transifex for our site so people can translate it. https://www.transifex.com/

**Comment by MegaApuTurkUltra** [comment]
Someone move this to JIRA please.

Good idea though.

**Comment by andrewjcole** [comment]
I could help with French. :P
