### ISSUE TITLE
Local uploader

### ISSUE THREAD

**Issue by Thegowgeofficial** [OpenSprites/OpenSprites#149]
What you guys think about software that uploads files directly from the client to the website?
The files would sync with the website without the user going on the website, reducing navigation time and making OpenSprites easier to use.

TheGowgeOffcial

**Comment by GrannyCookies** [comment]
Heh, maybe.
I don't know any languages that can be made into software for Win/Mac/Linux, but I _can_ port to ChromeOS / the Chrome Web Store.

Matu is skilled at Java, though.

**Comment by andrewjcole** [comment]
Aren't there things you can use to make apps with web technologies?

**Comment by MegaApuTurkUltra** [comment]
Yep, plenty. Chrome apps are an option, but we could make a full blown desktop webapp with tidesdk or something similar. However we should actually get OS finished and running first :P

**Comment by andrewjcole** [comment]
Mobile app?

**Comment by GrannyCookies** [comment]
"However we should actually get OS finished and running first"

**Comment by The-Cheese-Eater** [comment]
""However we should actually get OS finished and running first""

**Comment by andrewjcole** [comment]
I'd add more quotations, but nah.
