### ISSUE TITLE
Running on the Hyperboria network?

### ISSUE THREAD

**Issue by The-QullzToxic** [OpenSprites/OpenSprites#150]
I just thought having it on the dark net would be 1337...

https://hyperboria.net/
Its practically a mesh system

**Comment by The-Cheese-Eater** [comment]
I wouldn't call that the dark-web... Anyhow, we should keep this as transparent as possible.

**Comment by andrewjcole** [comment]
The site won't even load for me... :stuck_out_tongue:

**Comment by The-Cheese-Eater** [comment]
It's HTTPS, just use the HTTP prefix.

**Comment by MegaApuTurkUltra** [comment]
Nah. We don't want to be associated with the dark net, that's a bad place. <sub><sup>(Terrorists, drug lords, you name it)</sup></sub>How can we gain the trust of the ST like that?

**Comment by The-QullzToxic** [comment]
Meh :3
