### ISSUE TITLE
Migrating dev site to main domain

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#151]
I put this here so everyone reads it; I know that a few people aren't fans of JIRA. :stuck_out_tongue:

Quite a few people want the developer site moved to the main domain because it's getting annoying. While this is possible, it would break a few things and could possibly mislead people into thinking we are finished. I'm willing to move the site over after hearing everybody's opinions, and a way to notify our users (eg, a banner) that we are not finished.

**Comment by andrewjcole** [comment]
It would make things a lot easier, but there would be a lot of links and code to fix.

**Comment by The-Cheese-Eater** [comment]
Yeah

**Comment by 109C** [comment]
>It would make things a lot easier, but there would be a *lot of links and code to fix*.

That only happens if URLs are hardcoded... :/

**Comment by MegaApuTurkUltra** [comment]
Which, unfortunately, they are. All of my links to dev.opensprites have used some sort of global variable (ie, I introduced the `OpenSprites.domain` field in JS code) but there's a lot of hardcoding everywhere. A simple file search and replace should make this pretty easy to fix though.

**Comment by The-Cheese-Eater** [comment]
So shall I go ahead?

**Comment by GrannyCookies** [comment]
Go ahead. Merge the blog too

**Comment by GrannyCookies** [comment]
Also the search and replace'd be easy enough

**Comment by The-Cheese-Eater** [comment]
Righto, I'll do this soon. If you experience problems, you can count on this being the fault.

**Comment by GrannyCookies** [comment]
COMPLETED.
