### ISSUE TITLE
Wrap text on Blog page

### ISSUE THREAD

**Issue by Sonickyle27** [OpenSprites/OpenSprites#152]
Oops. The text breaks free to the right of the page, expanding it horizontally.
![screenshot from 2015-05-06 13 27 31](https://cloud.githubusercontent.com/assets/4775038/7492837/63d0623a-f3eb-11e4-93df-baaeeb803c70.png)

**Comment by GrannyCookies** [comment]
Er, not it doesn't.

**Comment by The-Cheese-Eater** [comment]
It does for me as well. :P

**Comment by GrannyCookies** [comment]
hmmmmmmmmmmmmmmmmmmmmm

**Comment by Rumanti** [comment]
Whoops.
Anyway, I fixed it on this commit (how do you reference commits O.O)
https://github.com/OpenSprites/OpenSprites/commit/8676fca570516dd69abc3c0fb2d592170e6c021e

**Comment by MegaApuTurkUltra** [comment]
@Rumanti I think you figured it out :P

You just paste the link and GitHub does the rest
