### ISSUE TITLE
I'm inactive for some time, sorry

### ISSUE THREAD

**Issue by Firedrake969** [OpenSprites/OpenSprites#154]
can't say when I'll join back :L

**Comment by 109C** [comment]
I think the "short term" label should be right... unless you'll be gone for longer.

**Comment by Firedrake969** [comment]
not for the summer for sure, can't say past that

**Comment by The-Cheese-Eater** [comment]
Sorry to hear! You're welcome to come back any time you can; just drop us a message over on Gitter, the main and most active way we communicate.

**Comment by jbayfield** [comment]
Aw, hope to see you back after summer :(
