### ISSUE TITLE
Site Redesign

### ISSUE THREAD

**Issue by jayforsythe** [OpenSprites/OpenSprites#16]
I have found out a way to mimic the Scratch site design. I figured this will make it look more friendly and Scratch-ish if we change the design to be like this. I have made a mockup of the site, here is a sample.
![capture](https://cloud.githubusercontent.com/assets/9374093/6112160/3186ba36-b05c-11e4-9ec5-3f5a883e79db.JPG)

Now doesn't that look good? I think so!
Please take this into consideration.

**Comment by The-Cheese-Eater** [comment]
I've read the topic, and I like it! Could you push the changes, please?

**Comment by jayforsythe** [comment]
another thing - we should change the repository so it's OpenSprites.github.io - github provides free hosting! Then we could just work off of that! I'll go ahead and make opensprites.github.io , and we can delete it if we don't like it.

**Comment by jayforsythe** [comment]
never mind, I can't make it. could you?

**Comment by GrannyCookies** [comment]
I will.

**Comment by GrannyCookies** [comment]
What's the code for the redesign?

**Comment by The-Cheese-Eater** [comment]
I asked chocolatepi to push his designs to a new directory, but I don't think he got around to it yet .:P

**Comment by GrannyCookies** [comment]
Okay. Can you see the new issue I just opened up?

**Comment by jayforsythe** [comment]
accidentally deleted the page. have to re-code it.

**Comment by The-Cheese-Eater** [comment]
That's a shame! D: Were you using Windows? I know you know, but have you tried looking at previous versions of the containing directory? Perhaps its in the recycle bin?

**Comment by jayforsythe** [comment]
it's saying "failed to sync this branch" whenever I try to sync it from the client.

**Comment by The-Cheese-Eater** [comment]
Sorry if I sound stupid, but do you actually have the files till on your computer? Can you make your own separate repo and I merge them?

**Comment by jayforsythe** [comment]
I can make my own separate repo, I have all the files. just tell me what to do ;)

**Comment by jayforsythe** [comment]
Gonna make one later, can't do much right now.

**Comment by The-Cheese-Eater** [comment]
When you feel ready, just create a new repo and push your changes to it as normal. I'll do stuff from there. :)

**Comment by jayforsythe** [comment]
github.com/jayforsythe/OpenSprites-JayForsythe

**Comment by The-Cheese-Eater** [comment]
Great, thanks! Lets see what everyone else thinks, and then we can add it and tweak it. :)

**Comment by GrannyCookies** [comment]
Wow, very cool! I think we should change up a couple things though.
By the way, I changed the indev page and added a 404 page.
See http://opensprites.x10.mx/notarealfolder/ for the 404.

**Comment by The-Cheese-Eater** [comment]
What sort of things are you suggesting?

**Comment by GrannyCookies** [comment]
Er... just simple things like the links I made for the 404 page (underlines etc)

**Comment by Rumanti** [comment]
Looks good! I'll try to tinker with some of the code later ;)

**Comment by GrannyCookies** [comment]
Implemented.
