### ISSUE TITLE
Lightspeed Rocket blocks opensprites.org

### ISSUE THREAD

**Issue by jbayfield** [OpenSprites/OpenSprites#163]
Lightspeed's web filtering systems currently block opensprites.org as the category 'Alcohol'.

This is obviously wrong and needs to be fixed.

**Comment by The-QullzToxic** [comment]
Obviously picks up sprit

**Comment by MegaApuTurkUltra** [comment]
Yet another example of how stupid the filter is. I hope you and cheese can get this sorted out.

**Comment by jbayfield** [comment]
This has been resolved but not in the way I had hoped. Category changed to forums.

**Comment by MegaApuTurkUltra** [comment]
Oh wow. Keep at it, we're supposed to be educational like scratch, so we shouldn't be blocked.

**Comment by The-Cheese-Eater** [comment]
@jbayfield Would you be able to send me a copy of your correspondence with Lightspeed? I'm not pleased that OpenSprites has been branded forums. Scratch has forums, but it's still an educational site.

**Comment by djdolphin** [comment]
Maybe changing the forum tab's name to "Discuss", like on Scratch, would help?

**Comment by The-Cheese-Eater** [comment]
I like the idea of changing the name to "Discuss", although I want to make sure we maintain a certain difference to Scratch.

**Comment by Rumanti** [comment]
**Synonyms of discuss:**
agitate, argue, bandy, bat (around or back and forth), canvass (also canvas), debate, dispute, hash (over or out), moot, talk over
**Similar words:**
 review, speak (about), talk (about); broach, introduce, propound, raise, stir up; forge, hammer out, talk out, thrash (out), wrestle (with); chew over, consider, deliberate, weigh
_None of those seems right.._
http://www.merriam-webster.com/thesaurus/discuss

**Comment by liam4** [comment]
Really? I like "hammer out".

**Comment by Rumanti** [comment]
It does not matter whether you like it or not, lol. "Hammer out" doesn't sound "educational" and probably will scare peoples (and or their parents). xD

**Comment by Firedrake969** [comment]
we still need to hammer out the right name for the forums :P

**Comment by The-Cheese-Eater** [comment]
I think we'll have to go with Discuss unless we can thing of an alternative?

**Comment by andrewjcole** [comment]
Here are some options: 
• Discuss
• Forums
• Talk
• Converse
• Say stuff
• Verbally Communicate
• Partake in a conversation

**Comment by Rumanti** [comment]
The last two are the best ideas @andrewjcole XP

**Comment by MegaApuTurkUltra** [comment]
I actually like "Talk"

**Comment by djdolphin** [comment]
@MegaApuTurkUltra I have a feeling that if it was changed to "Talk", OpenSprites would be recategorized as a chatroom.

**Comment by The-Cheese-Eater** [comment]
@djdolphin I think that would happen too.
