### ISSUE TITLE
Make assets actually stored by their hash instead of a random ID

### ISSUE THREAD

**Issue by jbayfield** [OpenSprites/OpenSprites#165]
I'm not sure why I decided not to do this. If I can remember why (maybe it was a good reason) then I might close this issue)

**Comment by bobbybee** [comment]
@jbayfield Doesn't sound like a good idea! How are you dealing with collisions?

**Comment by MegaApuTurkUltra** [comment]
Remember that it's not jbayfield opening these. I actually opened this on jira and a bot synced this here. 

Of course collisions right now are not handled well either. The chances of one happening are really low, however I've been thinking about some sort of system to handle them. 

I'll probably close this issue. It's too much work to implement. I can figure out some other way to support unlisted uploads.
