### ISSUE TITLE
OS server not able to tell client IPs

### ISSUE THREAD

**Issue by jbayfield** [OpenSprites/OpenSprites#166]
All IPs look like 10.10.10.4 to the server.

**Comment by The-QullzToxic** [comment]
You need this?

**Comment by MegaApuTurkUltra** [comment]
Yes, we do. For analytics and administration (specifically, potentially required IP bans which jbayfield already has had to do for gwiddle services)

**Comment by MegaApuTurkUltra** [comment]
Potential solution: Use `X-Forwarded-For` which I think nginx sets.

**Comment by The-Cheese-Eater** [comment]
This isn't really an issue anymore.
