### ISSUE TITLE
Make Carousels

### ISSUE THREAD

**Issue by liam4** [OpenSprites/OpenSprites#170]
The carousels have not been made yet, as you can tell by this screenshot:

![screen shot 2015-09-15 at 7 45 39 pm](https://cloud.githubusercontent.com/assets/9948030/9892123/3dd8335a-5be2-11e5-940f-d05a8e66541e.png)

We should probably finish those..

**Comment by Rumanti** [comment]
For Top Collections, someone should implement front-end for collections **first**.. _looks at myself_

**Comment by The-Cheese-Eater** [comment]
I'm pretty sure we have the back-end up to support the carousels, so this feature is waiting for someone to make it.
