### ISSUE TITLE
Make dropdown menus distinct from other solid-green elements

### ISSUE THREAD

**Issue by liam4** [OpenSprites/OpenSprites#171]
The easiest way to show this is when you hover over the **Browse** menu at the top of the homepage, which will make the menu blend in with the **OpenSprites is in development!** alert:

![screen shot 2015-09-15 at 8 10 59 pm](https://cloud.githubusercontent.com/assets/9948030/9892495/c06b9f48-5be5-11e5-92cc-ec34e49ee612.png)

**Comment by Rumanti** [comment]
Why don't you use Atlassian?? :stuck_out_tongue_winking_eye:  Nah just kidding. Maybe box-shadows.. Hmm.

**Comment by MegaApuTurkUltra** [comment]
Yeah I think I did something for this but it got reverted because I suck at making stuff look good. A box shadow sounds good, just classic `2px 2px 5px black` will probably do the trick

**Comment by Rumanti** [comment]
----> 138ffc444e151a49842905d98423fe3b10290dc1

**Comment by liam4** [comment]
Because I don't get on Atlassian every day.. :package:

**Comment by Rumanti** [comment]
Fixed it. Looks good to me.

**Comment by liam4** [comment]
Agreed, great, just make the menus `z-index` lower than the tool bar's so that the shadow doesn't go up on to the tool bar.
