### ISSUE TITLE
Change logo padding in toolbar

### ISSUE THREAD

**Issue by liam4** [OpenSprites/OpenSprites#172]
(Haha. I like making issues >:D)

The padding for the logo in the toolbar is really off-centered.

![screen shot 2015-09-17 at 5 04 08 pm](https://cloud.githubusercontent.com/assets/9948030/9944497/10c3b60a-5d5e-11e5-902d-a9559793160a.png)

The padding beside the **S** is a lot more than the padding beside the OS logo badge thing. Might not be a bad idea to increase it slightly to match.

**Comment by DM5555** [comment]
TBH It looks alright atm

**Comment by Firedrake969** [comment]
it bugs me

**Comment by DM5555** [comment]
Fine, I'll see if It's the svg or the css and fix it

**Comment by DM5555** [comment]
Actually the logo is cropped already, but with the shadows included, if I were to make it smaller then I would have to cut parts of the logo short
