### ISSUE TITLE
Forum footer and main footer look different

### ISSUE THREAD

**Issue by liam4** [OpenSprites/OpenSprites#173]
Forum footer:

![screen shot 2015-09-18 at 1 40 25 pm](https://cloud.githubusercontent.com/assets/9948030/9965380/4759761a-5e0c-11e5-8444-5e6b7aa20126.png)

I prefer the main footer (obviously):

![screen shot 2015-09-18 at 1 41 22 pm](https://cloud.githubusercontent.com/assets/9948030/9965179/e1662f34-5e0a-11e5-9b34-be54badd52c8.png)

So yes, we should probably try to make them at least similar.

**Comment by Rumanti** [comment]
I designed the main footer yay (for responsiveness, try it) but dunno how to set up the footer on the forums..
GrannyCookies is the one who managed the forum haxx, so I assigned him :package:

**Comment by liam4** [comment]
Good idea lols.

**Comment by liam4** [comment]
Also footer looks great!

**Comment by GrannyCookies** [comment]
When you assign me stuff, notify me on gitter, I don't check my github notifications :P

**Working on it.**

**Comment by GrannyCookies** [comment]
The code is in, but **an admin needs to push to the non-osdev site for it to work**.

**Comment by The-Cheese-Eater** [comment]
All done. The CSS needs tweaking, but nothing major. 
I'm also looking into allowing the team to run OSDEV builds on TeamCity independently.

**Comment by GrannyCookies** [comment]
@The-Cheese-Eater Great.

**Comment by liam4** [comment]
Cool!
