### ISSUE TITLE
Don't make a specific mobile app

### ISSUE THREAD

**Issue by robinp7720** [OpenSprites/OpenSprites#175]
Just a recommendation. Just make it a responsive web design.
Assuming that https://github.com/OpenSprites/OpenSprites/tree/master/public_html/app is a "mobile app"

**Comment by Rumanti** [comment]
For your information, we are (trying to) making the website design as responsive as possible. 

.. Though I forgot _why_ some of the team wants to create an app.. It was decided months ago and no progress.

**Comment by Firedrake969** [comment]
I think it was primarily arinerron's idea.

**Comment by Rumanti** [comment]
@Firedrake969: We already decided to make an app months before Arinerron joined. And during your inactivity, too. :P

**Comment by Firedrake969** [comment]
oh
