### ISSUE TITLE
Use prepared statements

### ISSUE THREAD

**Issue by robinp7720** [OpenSprites/OpenSprites#176]
PDO and mysqli both support them. This is open to serious sql injection!

**Comment by MegaApuTurkUltra** [comment]
[-_-](https://github.com/OpenSprites/OpenSprites/blob/master/public_html/assets/includes/database.php#L180)

**Comment by octad** [comment]
Hey Mega what happened on Scratch

**Comment by Rumanti** [comment]
@octad .. This is not the place to ask such questions.. .-.
