### ISSUE TITLE
Make the webapp independant of opensprites.org

### ISSUE THREAD

**Issue by robinp7720** [OpenSprites/OpenSprites#177]
Would make it easier for everyone

**Comment by Firedrake969** [comment]
that's the webapp's URL.  lol

**Comment by robinp7720** [comment]
@Firedrake969 many things such as the register page just link to opensprites.

**Comment by Firedrake969** [comment]
...what do you mean?

**Comment by robinp7720** [comment]
@Firedrake969 https://github.com/OpenSprites/OpenSprites/blob/master/public_html/register/index.php

**Comment by Firedrake969** [comment]
yeah it's a page on the site lol http://prntscr.com/8kuxyg

**Comment by robinp7720** [comment]
"independant of opensprites.org"

**Comment by MegaApuTurkUltra** [comment]
I think what you mean to suggest is that we should avoid hard-coding the site domain in stuff. A refactor for that might be good.

**Comment by Firedrake969** [comment]
Yeah, wouldn't be too hard
