### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by Firedrake969** [OpenSprites/OpenSprites#18]
How do we want the registration flow to go?  I've installed the PHP Simple HTML DOM plugin, but we'll need to develop a flow for registration w/Scratch linkage.

**Comment by jayforsythe** [comment]
Perhaps a separate page?
I could make the bare HTML of the registration page, as I know nothing of PHP and/or SQL (or whatever we're using). Just ask if you need anything

**Comment by Firedrake969** [comment]
I'm actually talking about how registration and linking to your Scratch account/verifying should work

**Comment by The-Cheese-Eater** [comment]
Didn't we come to a conclusion that using the project comments API method was the best way?

**Comment by jayforsythe** [comment]
Ooh! Yeah, we could make an "OpenSprites" account and have a verification project.

**Comment by Firedrake969** [comment]
@all involved

I mean should the user register and then get a string to put in their comment/whatever, or vice versa, or what?

**Comment by GrannyCookies** [comment]
I think that they should get a code generated from their ip address and then that is stored in the server. Next they should comment on the OpenSprites register project with that code, similar to the wiki.

**Comment by jayforsythe** [comment]
example:

Almost done!
Copy and paste this code into the comments section in scratch.mit.edu/projects/XXXXXXXX:
[some encrypted thing based on their IP]

then it would set up a bot, maybe, that watches the project for any new comments containing that code?

**Comment by GrannyCookies** [comment]
@Firedrake969 Instead of a bot, it the user should click "Done".

**Comment by GrannyCookies** [comment]
http://scratch.mit.edu/users/OpenSprites/

**Comment by Firedrake969** [comment]
ok, have an idea how to implement.  will do so when I have time.

**Comment by GrannyCookies** [comment]
@Firedrake969 I need help.
