### ISSUE TITLE
Finish carousels

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#180]
The carousels currently all show the same thing. What we really need is to remove the selection bar, and set the carousels to display a permanent selection, namely, what is written in the title box above each carousel.

Assigning to MATU because he has experience with the carousels.

**Comment by DM5555** [comment]
The same-thing carousels was my fault

**Comment by Firedrake969** [comment]
Who made the carousel CSS?

**Comment by DM5555** [comment]
dunno

**Comment by The-Cheese-Eater** [comment]
MATU I think

**Comment by The-Cheese-Eater** [comment]
@DM5555 Seems to have the first two carousels under control.

**Comment by Rumanti** [comment]
hai can u feature mai stuff plz
...
Seriously, though, feature some stuff please. To be honest, partially filled carousels look horrible.

**Comment by DM5555** [comment]
@Rumanti As far as I know there is no feature button at the moment, I'll see If I can implement it

**Comment by The-Cheese-Eater** [comment]
I've featured three things so far (three is better than two :P)

It's done via the database at the moment, by basically giving a value in the IsFeatured? column. Obviously not ideal.

**Comment by The-Cheese-Eater** [comment]
The carousels were finished a while ago by GrannyCookies.
