### ISSUE TITLE
We've decided on the licensing of media, yes?

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#183]
It seems to be a grey area that I've forgotten about. I think we should follow Scratch with the Attribution-ShareAlike 2.0 Generic license, although I'm not sure about freedom to use commercially. If we disallowed commercial use, this would create a bit of friction with using media from OS in projects, yes?

Whatever we decide on, I'll make it my job to document the decision; we should also make a note of having a link to the license on the page of the media and when a user uploads something, they must agree to the license.

**Comment by Rumanti** [comment]
Wait aren't the media MIT Licensed? Or is it only the site?

**Comment by The-Cheese-Eater** [comment]
The site and source is licensed under the MIT license. To quote the footer, "Unless where otherwise stated, this site is licensed under a MIT license." Assets don't apply to this license.

**Comment by Rumanti** [comment]
This sounds perfect. http://creativecommons.org/licenses/by-nc-sa/4.0

**Comment by The-Cheese-Eater** [comment]
I think for maximum compatibility we need to go with the license Scratch uses, http://creativecommons.org/licenses/by-sa/2.0/deed.en. Agreed?

**Comment by Rumanti** [comment]
To be honest, I don't think people should be able to use media shared on OpenSprites commercially..

**Comment by The-Cheese-Eater** [comment]
Neither do I, but we may face issues with letting people using media on OS on Scratch. In effect, if someone uploaded media from OS to Scratch, it would become licensed under Scratch's license (http://creativecommons.org/licenses/by-sa/2.0/deed.en), and it would be allowed to use commercially anyway. Whatever license we implement here, you'll still be able to use media commercially some how. It's best just to follow Scratch.

**Comment by liam4** [comment]
+1

**Comment by Firedrake969** [comment]
+1

**Comment by Rumanti** [comment]
That makes sense +1

**Comment by The-Cheese-Eater** [comment]
Righto, I guess that is sorted then. I'll edit the documents.

**Comment by Rumanti** [comment]
Seems solved.
