### ISSUE TITLE
Ocean theme turns screen black

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#184]
Functionality can be returned by clearing one's cookies and cache.

**Comment by mhsjlw** [comment]
I have just experienced this same bug.

**Comment by The-Cheese-Eater** [comment]
Just pushed a commit to disable the ocean theme. I'll re-enable when the style is bug free.

**Comment by The-Cheese-Eater** [comment]
Themes aren't really a priority.
