### ISSUE TITLE
Can't upload hidden assets

### ISSUE THREAD

**Issue by liam4** [OpenSprites/OpenSprites#187]
I added a hidden asset to my upload list.

However, when I click on Submit, the following error gets logged:

```
TypeError: hiddenAssets.append is not a function
```

So hiddenAssets isn't being defined (properly) somewhere..?

**Comment by The-Cheese-Eater** [comment]
It is a feature that hasn't been implemented. I only want it to show for images, so if someone wishes to host an image for the forums it won't clog up the site.

**Comment by Arinerron** [comment]
Any updates on this?

**Comment by Rumanti** [comment]
@Arinerron:

# nope

**Comment by liam4** [comment]
# _**`nope u w0t m8`**_
ftfy

**Comment by The-Cheese-Eater** [comment]
Since we're working on a separate hosting service, this isn't needed any longer.
