### ISSUE TITLE
Errored GIF upload isn't being displayed?

### ISSUE THREAD

**Issue by liam4** [OpenSprites/OpenSprites#188]
I tried to upload a 3 MB GIF. After the upload request finished, the following object got logged to my console:

```js
{
  ...
  results: [
    {
      hash: "",
      image_url: "N/A",
      message: "Sorry! Our servers encountered an error with your upload request. Make sure each individual file is less than 2MB (error code 1)",
      status: "error"
    }
  ]
  ...
}
```

However nothing outside of looking through an object in the console told me my asset upload had errored.

High-priority?

**Comment by The-Cheese-Eater** [comment]
I'm guessing that along with the other upload errors we keep getting that this has something to do with size limits. For example, I can upload small images but not larger ones. Same with audio. I'll assign @MegaApuTurkUltra because he has the most experience with this.

**Comment by liam4** [comment]
I get _why_ it doesn't upload, but we need to get a dialog to appear if the image doesn't upload properly

**Comment by The-Cheese-Eater** [comment]
Pretty sure an error is displayed near the top of the page?

**Comment by The-Cheese-Eater** [comment]
Merge with #199
