### ISSUE TITLE
Fix the "image enlarger" feature bug

### ISSUE THREAD

**Issue by Rumanti** [OpenSprites/OpenSprites#189]
For some reason, the "image enlarger" doesn't work.. You click the image, and you got the "dark-box" all right, but no enlarged image.. 

http://opensprites.org/forums/?p=38-larger-images/p1#p176

**Comment by The-Cheese-Eater** [comment]
Yeah, we need to fix that :P

**Comment by The-Cheese-Eater** [comment]
GC's faulty CSS property find has fixed this. :D
