### ISSUE TITLE
Image previews don't enlarge

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#192]
When clicking on an image on its 'profile', the box expands, but the image doesn't. Has been reported a number of times.

**Comment by The-Cheese-Eater** [comment]
Whoops, already reported by @Rumanti

**Comment by liam4** [comment]
lolol

**Comment by Rumanti** [comment]
:package:

**Comment by 109C** [comment]
:box:

**Comment by 109C** [comment]
Whoops, wrong issue...

**Comment by GrannyCookies** [comment]
Easy fix- use css `background: url('path/to/image') contain 50% 50%;`.
