### ISSUE TITLE
Footer on forums

### ISSUE THREAD

**Issue by JelloMonster118** [OpenSprites/OpenSprites#194]
doesn't look very good.

**Comment by Arinerron** [comment]
I've been noticing that too... I'll talk to them about it...

**Comment by Rumanti** [comment]
This issue is a duplicate of an issue already created by Liam4. Sorry can not link now, got to go to 800+ km away to Yogyakarta.

**Comment by liam4** [comment]
\*cough\* \*cough\* #173 :package:
