### ISSUE TITLE
New CSS messes up blog

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#196]
Check OSDEV, most of the elements including the nav are messed up.

**Comment by liam4** [comment]
That's treu.

**Comment by GrannyCookies** [comment]
:/ tbh I think the blog needs a rewrite server-side

**Comment by Arinerron** [comment]
Update: I've added a temporary fix which should work for now. Unfortunately, I can't test it due to the amount of time it is taking for osdev to update, and the fact that it is 1:00 in the morning. :stuck_out_tongue_winking_eye:

**Comment by Arinerron** [comment]
Closing issue: My latest commit fixes this CSS mess up. There was a rouge `height: 35px;` line in there. :stuck_out_tongue_winking_eye:
