### ISSUE TITLE
Warm Theme stops Register page from loading

### ISSUE THREAD

**Issue by Arinerron** [OpenSprites/OpenSprites#197]
Go to the register page & switch to warm theme :P

**Comment by The-Cheese-Eater** [comment]
Merge with #198

**Comment by Arinerron** [comment]
@The-Cheese-Eater They are two completely different issues though :/

**Comment by The-Cheese-Eater** [comment]
Yeah, but pretty much all of the themes are broken.

**Comment by QuillzLouis** [comment]
Not for long (Hopefully)
