### ISSUE TITLE
Themes don't fully work

### ISSUE THREAD

**Issue by Arinerron** [OpenSprites/OpenSprites#198]
Ever since the new site design update, the themes no longer change all of the colors, thus, the site looks messy. For an example, try Dark then Warm theme on the front page (opensprites.org), and notice the cards don't change their backgrounds. This issue is not only with the Dark and Warm theme, I just used those two because they are the most different, and I wanted to show you that it is not just one theme's fault. :P

**Comment by QuillzLouis** [comment]
I'll try and fix this tommorow

**Comment by QuillzLouis** [comment]
I has fixed this, I shall do a push request.

**Comment by QuillzLouis** [comment]
Why do we need themes?
There a pain to keep updating

**Comment by Arinerron** [comment]
Lol whoops, accidently tapped close on my phone

**Comment by The-Cheese-Eater** [comment]
Themes aren't really a priority.
