### ISSUE TITLE
[BACKEND] 'Something bad has happened and our servers sent back a bad response'

### ISSUE THREAD

**Issue by Arinerron** [OpenSprites/OpenSprites#199]
'Something bad has happened and our servers sent back a bad response. Contact us if this continues'. This message occurs when doing certain actions that include (but are not limited to):
- Uploading resources and media
- Uploading new user photo

This is extremely important that this gets fixed @OpenSprites/backend-php , because the entire purpose of OpenSprites no longer works, due to this bug.

**Comment by Arinerron** [comment]
^ I can't assign the entire backend team :P

**Comment by liam4** [comment]
> I can't assign the entire backend team :P

whoa @github team please add assigning organization groups o_o

**Comment by Firedrake969** [comment]
lol php

**Comment by GrannyCookies** [comment]
> lol php
this.

**Comment by 109C** [comment]
I suppose this is why one should not push to master.

**Comment by Firedrake969** [comment]
lol pushing directly to prod

**Comment by The-Cheese-Eater** [comment]
This pretty much happens with most uploads.

**Comment by trumank** [comment]
Has anyone tried a `$ git bisect`?

**Comment by Tymewalk** [comment]
@trumank I'll take a look. Does anyone know of the last commit this worked at?

**Comment by The-Cheese-Eater** [comment]
It hasn't ever been completely reliable, but it was workable in earlier versions of the site - hundreds of commits down the line.

**Comment by Tymewalk** [comment]
@The-Cheese-Eater Do you have an idea of when that was, or at what release?
Also, how would I test the backend?

**Comment by The-Cheese-Eater** [comment]
Trying to look at when the code worked probably won't help here, this is more analysing and fixing bugs and problems. Testing code is a bit difficult because OpenSprites is built around our setup and requires two databases to function. Testing is basically revising over changes for common errors and pushing it to GH, where I can update the site.

**Comment by QuillzLouis** [comment]
Still, something should be done, it is much more productive to be able to
find errors in your code instantly.

**Comment by Tymewalk** [comment]
@The-Cheese-Eater @QuillzLouis Either way, it's better than nothing.
Is there a way to get specific errors from the server? Maybe we're just missing a semicolon :stuck_out_tongue:

**Comment by Tymewalk** [comment]
Checked the PHP files with `php -l`, looks like it's not just a missing semicolon.

**Comment by Arinerron** [comment]
Thank you @The-Cheese-Eater!
