### ISSUE TITLE
Navigation styling

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#20]
Navigation styling is not appearing on every page. I think it is because somebody commented out the link to the CSS, but if they did then how does it render correct on the main page? :/

**Comment by GrannyCookies** [comment]
I did the main page. The names of classes are different, that's why. Sorry.

**Comment by The-Cheese-Eater** [comment]
Righto

**Comment by GrannyCookies** [comment]
Do you like the nav now? :P
