### ISSUE TITLE
OpenSprites Resources icon missing on all pages?

### ISSUE THREAD

**Issue by Arinerron** [OpenSprites/OpenSprites#200]
I know this is a known issue, this is just a reminder for people who don't know what to do currently

https://opensprites.org/

**Comment by Arinerron** [comment]
I'm putting this task on @The-Cheese-Eater :stuck_out_tongue_winking_eye: I remember him mentioning this before, so he must know more about this. :P

**Comment by liam4** [comment]
https://github.com/OpenSprites/OpenSprites/blob/master/public_html/navbar.php#L79

This is empty - shouldn't there be an `img` tag there, like [here](https://github.com/OpenSprites/OpenSprites/blob/master/public_html/navbar.php#L13)?

**Comment by liam4** [comment]
This definitely isn't low priority! How do people know if they're on OS or not if the logo isn't there? :P

**Comment by Arinerron** [comment]
Fine liam4 :stuck_out_tongue_winking_eye:

**Comment by Arinerron** [comment]
![screenshot_2016-02-18-17-21-36](https://cloud.githubusercontent.com/assets/3926753/13163721/25e90a2e-d664-11e5-9d6b-58c705b126dc.png)
How will they know? :P

**Comment by The-Cheese-Eater** [comment]
When I ran the http to https find and replace job, it must have replaced some info in the svg file, making it go odd. I've restored the original images from backup. In my browser the image is still hidden until enabled in inspect element. Does this happen to anyone?

**Comment by liam4** [comment]
It appears right away for me.
