### ISSUE TITLE
Unable to go to user page from forum post

### ISSUE THREAD

**Issue by Arinerron** [OpenSprites/OpenSprites#202]
------

![screenshot from 2016-02-23 16 03 13](https://cloud.githubusercontent.com/assets/3926753/13271049/2e94f656-da47-11e5-8c5c-f05493a9ef5f.png)

------
In the forums, on a post, you can click the person's username to go to their profile page. Well, at least you are supposed to be able to click the username. When you click it, it goes to
`https://opensprites.orgusers/index.php?id=1` rather than `https://opensprites.org/users/index.php?id=1` (missing the slash). Easy to fix, and low priority.

**Comment by nanalan** [comment]
[This looks fixed.](https://github.com/OpenSprites/OpenSprites/blob/master/public_html/forums/core/lib/functions.render.php#L80)

**Comment by Arinerron** [comment]
Hmmm... It does look fixed, but it isn't.
On [this page](https://opensprites.org/forums/?p=50-verification-link-problem) for example, clicking his icon directs to https://opensprites.orgusers/index.php?id=109

**Comment by Arinerron** [comment]
Even weirder: Hovering over the icon has the correct link, but clicking on it gives you the link without the slash.

**Comment by Arinerron** [comment]
Speaking of [the example forum post](https://opensprites.org/forums/?p=50-verification-link-problem), I just read the post and realized he is experiencing a similar problem (where the slash is missing).

**Comment by Arinerron** [comment]
This is a higher priority issue since it is now affecting more than just one url, and users.

**Comment by nanalan** [comment]
:-1: Sounds like a bug with the OpenSprites server setup - @The-Cheese-Eater thoughts.
