### ISSUE TITLE
Do you need a front end developer?

### ISSUE THREAD

**Issue by QuillzLouis** [OpenSprites/OpenSprites#203]
Hi Louis/QuillzToxic Here,
I was wondering if you are after another front end developer, I have taken a course on programming and want to get onto a project to improve my skills

**Comment by The-Cheese-Eater** [comment]
I'm afraid that you've arrived a little too late; most of our frontend work had already been done!

**Comment by QuillzLouis** [comment]
What about issue 108?

**Comment by QuillzLouis** [comment]
And also, just a refresh, why did I get rekicked after you added me back in in issue #137

**Comment by QuillzLouis** [comment]
As far as I know, I'm still in the project, I just went inactive....

**Comment by Firedrake969** [comment]
I'm pretty sure being kicked out means being kicked out.

**Comment by QuillzLouis** [comment]
Actually if you read #137 "@The-QullzToxic we removed you because you seriously screwed code up. I know you used the command line thing, and you're new at it, but that's not really an excuse. If you know you're bad at the command line git, you should have used a GUI-based git, especially on a critical project like OpenSprites. You can test command line git all you want on your own repos.

What you did was pretty bad. You deleted tons of our code, and apparently screwed up the blog layout or something.

We didn't mean to hate when we removed you from the organization. We just can't afford huge code-deletions and stuff in the future.

Just because you do not have write permissions to the repo does not mean you can't contribute. You can create your own fork, work there, and send a pull request when you're done. You can still comment on our issues and commits too. If you show that you can make significant changes and handle git responsibly in your fork, we'll give you write permissions back.

To be clear, you are not banned from the organization entirely. We want to be nice and give you a second chance, it's just that we can't give you write permissions at the moment, because of what happened.

I'm unlocking this issue so you can comment back if necessary, however please be respectful when commenting (ie, don't call yourself an idiot, don't accuse anyone of hate, and keep the sarcasm to a minimum)." -MegaAptTurkUltra, and above James (Cheese) wrote 
"You know full well that we do not hate you quillz, I've known you for a year by now. I have invited him back into the team because this project deserves not to get into disputes. However, Quillz must understand this there is a limit to the amount of chances I can give before people start getting annoyed at having to revert changes all the time. With respect @andrewjcole, but you were not zeus trying to scrape backups from the developer site to patch the mess. I am acting as a admin within this project, and I intend to keep it that way; becoming a negotiator to solve personal disputes is certainly not high upon my agenda.

I'm tired of all that grumpy bore I just wrote, shall we have some lightheartedness and positivity again? :)"

Both say I am still in the group, I am wondering if Zeusking (Or what ever you call the head of gwiddle) may of kicked me, I'm just can't remember what happend between this event.

**Comment by QuillzLouis** [comment]
Sorry about my huge quotes

**Comment by QuillzLouis** [comment]
As of further point that Zeus may of kicked me, when I asked for a gwiddle account he first said something along the lines of "You can not revive a gwiddle account because of a unsolved argument".

Oh and Zeus, what happend with your DMCA strike agenst me with Scratch Mobile?

**Comment by Firedrake969** [comment]
Read this.
> Just because you do not have write permissions to the repo does not mean you can't contribute. You can create your own fork, work there, and send a pull request when you're done. You can still comment on our issues and commits too. If you show that you can make significant changes and handle git responsibly in your fork, we'll give you write permissions back.

I would say you need to prove your aptitude with git before letting you back in, or doing some pull requests instead of getting write permissions.  Preferably the latter.

**Comment by QuillzLouis** [comment]
Yeah, but you all seem to talk on gitter, and its sorta the only way to
receive tasks.

**Comment by QuillzLouis** [comment]
Anyway, I'm going to have a go at fixing the themes.

**Comment by Firedrake969** [comment]
As if we're productive on Gitter :package: 
Well, there are tasks here you can start on.

**Comment by QuillzLouis** [comment]
Gitter is easier to get hold of people on, because your so active over
there (Trust me.)

**Comment by Firedrake969** [comment]
We all see this too.  Maybe I'm the only one bothering to reply to you?
Considering the fact that you're not in our Gitter rooms, though, I would say that I have more authority about that than you...  :/  The productivity is on Github, and the offtopicness is on Gitter.  Just make PRs.  Then we'll see.

**Comment by Arinerron** [comment]
> We all see this too. Maybe I'm the only one bothering to reply to you?
Considering the fact that you're not in our Gitter rooms, though, I would say that I have more authority about that than you... :/ The productivity is on Github, and the offtopicness is on Gitter. Just make PRs. Then we'll see.

^ that

**Comment by QuillzLouis** [comment]
@Firedrake969 Technically I made gitter #92

**Comment by Firedrake969** [comment]
Ok... are you trying to imply anything?

**Comment by QuillzLouis** [comment]
Not really, working on the themes now.
