### ISSUE TITLE
Please remove the tag clutter

### ISSUE THREAD

**Issue by Firedrake969** [OpenSprites/OpenSprites#204]
Just one example - http://prntscr.com/a7zf6y
Two joke tags.
Contrary to popular belief, it's not a bug and a feature at the same time - either existing code is broken or you're implementing a new feature.  Fixing an old thing or making a new thing (even from a working old thing).
The other issues are similar.

Honestly it's just that the tag section seems huge and ugly IMHO

**Comment by QuillzLouis** [comment]
Well, it could be both (The example flew out of my head) but I agree

-Random guy who has nothing to do with the project

**Comment by Arinerron** [comment]
There, legitimate tags.

**Comment by Arinerron** [comment]
^ :stuck_out_tongue_winking_eye:

**Comment by The-Cheese-Eater** [comment]
I've removed the joke tags. Now it's up to everyone else to choose the appropriate ones.

**Comment by Firedrake969** [comment]
:)
