### ISSUE TITLE
Selfhosting directs to opensprites.org ._.

### ISSUE THREAD

**Issue by QuillzLouis** [OpenSprites/OpenSprites#207]

**Comment by 109C** [comment]
How is this not a bug.

**Comment by The-Cheese-Eater** [comment]
He's talking about hosting a development copy locally, by the way.

No OS developer here uses a local copy because the whole website is specifically built around our setup and getting every link on the website to point to its root location instead of the OS domain isn't worthwhile.

**Comment by QuillzLouis** [comment]
It still is worthwhile what if you change domain? Find and replace could
fix this.

**Comment by The-Cheese-Eater** [comment]
Why would we ever change domain names?

**Comment by QuillzLouis** [comment]
You never know.

**Comment by Firedrake969** [comment]
Honestly, I agree with Quillz, if I'm reading this correctly - are you saying to not develop locally?

**Comment by QuillzLouis** [comment]
That would sorta work, l am suggesting a way to instantly test your code.

**Comment by Firedrake969** [comment]
unittestsunittestsunittestsunittests

**Comment by QuillzLouis** [comment]
Wut the hell

**Comment by The-Cheese-Eater** [comment]
https://lmddgtfy.net/?q=unittest

**Comment by Firedrake969** [comment]
Oh yeah you guys are using straight PHP aren't you lol
This is a great example of technical debt :P

**Comment by QuillzLouis** [comment]
A python library? I didn't think open sprites used python?

**Comment by Firedrake969** [comment]
Where did Python come into this?  o.o

**Comment by QuillzLouis** [comment]
Unittest

**Comment by Firedrake969** [comment]
That's not exclusive to Python :P

**Comment by GrannyCookies** [comment]
_To be honest the best way to fix these bugs is a rewrite._
/controversial

**Comment by The-Cheese-Eater** [comment]
^ pls rewrite in node k tnx bye

**Comment by Firedrake969** [comment]
that wouldn't be that bad :P

**Comment by QuillzLouis** [comment]
Pls rewrite in English merci

**Comment by 109C** [comment]
@QuillzLouis mais qui etait telephone?
