### ISSUE TITLE
Registration page

### ISSUE THREAD

**Issue by Firedrake969** [OpenSprites/OpenSprites#21]
Could someone make a layout of the registration page (in Site/register/index.php)?  Basically, what we'll need in terms of page content is a form for registration (which I can add/delete inputs of), an area for a 10-alphanumeric code (just use XXXXXXXXXX) and a button with an area by it for text (saying that the code has already been posted)

**Comment by Firedrake969** [comment]
Also, add styling to the registration page (http://opensprites.x10.mx/live/alpha/register/)

**Comment by Rumanti** [comment]
For styling, are you thinking of something like this? http://scratch.mit.edu/accounts/login/ By the way, is the navbar going to be included?

**Comment by Firedrake969** [comment]
Styling - I really don't care as long as it looks more than plain HTML :P  That's your job to design :3

**Comment by GrannyCookies** [comment]
I'll have a go.

**Comment by GrannyCookies** [comment]
Done.
