### ISSUE TITLE
Downloads don't carry their file extention

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#211]
Media files are not being downloaded as [MediaName].[FileExtension], but instead are being _named_ their original file extension. This causes the client computers to not recognise what program to open the media with. The server needs to specify the file type in downloads.

**Comment by liam4** [comment]
Was this fixed?

**Comment by liam4** [comment]
Looks like it was -- downloading [this](https://opensprites.org/users/mysterywave/d77207bc0461faa5d254a356bf1bd9d2/) gave me a file called "OpenSprites-Download.jpg". It'd be nice if the name of the upload was included in that file name somewhere though. Maybe open a new issue for that?

**Comment by The-Cheese-Eater** [comment]
The only way to keep the file extension was to remove the name of the asset from the download name. I'm hoping this is a temporary fix, and that someone in the chat will pick it up.
