### ISSUE TITLE
Site Logo

### ISSUE THREAD

**Issue by Rumanti** [OpenSprites/OpenSprites#22]
The logo [cauzality](http://scratch.mit.edu/users/cauzality/) had made very kindly for this project is really good, but it doesn't fit with the new site design. Any ideas? 

FYI, I have contacted cauzality about this.

**Comment by Firedrake969** [comment]
I must agree.

Maybe a blue square with OS linked in Scratch font and orange, like http://www.society43.com/v/vspfiles/assets/images/logos/Oregon%20State%20Logo.jpg?

**Comment by The-Cheese-Eater** [comment]
I think that the logo you have suggested could fit the site, but it would nice to have a full version of 'OpenSprites'. The style you linked above could be a favicon? I like how that image came from a sunglasses shop. :P

**Comment by Firedrake969** [comment]
As a favicon would be cool

**Comment by GrannyCookies** [comment]
@Firedrake969 Look at the navbar now, do you like it?

**Comment by Firedrake969** [comment]
Yeah, sure, though I don't quite understand the logo

**Comment by GrannyCookies** [comment]
:P it is temporary.

**Comment by Firedrake969** [comment]
Ok, cool

**Comment by jayforsythe** [comment]
really love the navbar! however, it'd be more clear to have the word "opensprites" instead of that simple "s" thing.

**Comment by andrewjcole** [comment]
@jayforsythe Added. It has no font now. Any ideas?

**Comment by Rumanti** [comment]
The updated logo cauzality made is nice, I actually liked it: http://imagizer.imageshack.us/a/img537/3149/JeCP3m.png

**Comment by GrannyCookies** [comment]
@Rumanti Yeah, I like Cauzality's logo. It also fits with the new navbar css design I made.

**Comment by GrannyCookies** [comment]
@jayforsythe Thanks! :D

**Comment by GrannyCookies** [comment]
@andrewjcole Problem is, it looks a bit.. bad.

**Comment by Rumanti** [comment]
Seems like we already have a site logo.
