### ISSUE TITLE
navbar.php extremely messy

### ISSUE THREAD

**Issue by Firedrake969** [OpenSprites/OpenSprites#23]
if nobody objects, I'm going to completely redo it (w/same content and styling, of course)

**Comment by GrannyCookies** [comment]
It's messy?

**Comment by GrannyCookies** [comment]
What's messy about it?

**Comment by Firedrake969** [comment]
Indenting is ugly, no comments on what is where, and <body> tags where there shouldn't be.  It'll be easier to remake it than to fix it.

**Comment by GrannyCookies** [comment]
You mean the code?
Not the actual outcome?

**Comment by Firedrake969** [comment]
Yes, the code.

**Comment by GrannyCookies** [comment]
I agree, the indenting is ugly.

**Comment by GrannyCookies** [comment]
All of it is :P

**Comment by Firedrake969** [comment]
Exactly, hence my asking whether nobody minds if I completely remake it (w/same output, of course)

**Comment by GrannyCookies** [comment]
I don't mind.

**Comment by Firedrake969** [comment]
Ok

**Comment by GrannyCookies** [comment]
You might as well.

**Comment by GrannyCookies** [comment]
We need to do the login page now too.

**Comment by Firedrake969** [comment]
I removed the login page because I'll make the navbar so that we can login from any page.
