### ISSUE TITLE
Indentation inconsistencies

### ISSUE THREAD

**Issue by bleush38p** [OpenSprites/OpenSprites#24]
Some files use two spaces, some four, some tabs, some seem to be picking and choosing throughout.

As a group can we agree upon a style for our code? My personal vote is two spaces, but if people like something else, we might want to go with tabs (then you can configure your editor however you like.)

**Comment by GrannyCookies** [comment]
I like tabs, but 4 spaces is fine with me :P

**Comment by bleush38p** [comment]
I think tabs might be best. It seems the most unselfish - as anyone can set their editor to the amount they like best.

Of course, redoing all of the indentation will completely ruin blames (one of the best named features here, in my opinion), but I think it's best if we maintain a similar coding style throughout.

**Comment by Firedrake969** [comment]
I like tabs too.

**Comment by 109C** [comment]
I vote for two spaces.

**Comment by bleush38p** [comment]
Reopening because it nothing's been actually changed. Are tabs cool with everyone?

**Comment by The-Cheese-Eater** [comment]
I'm cool with tabs myself

**Comment by Firedrake969** [comment]
same

**Comment by Rumanti** [comment]
Vote for tabs. Keyboard friendly.

**Comment by DM5555** [comment]
Tabs, Or 2 spaces if the file doesn't suppourt it

**Comment by liam4** [comment]
Tabs, but mine is auto-4 spaces. :P

**Comment by andrewjcole** [comment]
Tabs or 4 spaces is fine.
