### ISSUE TITLE
Variable naming/string enclosing conventions

### ISSUE THREAD

**Issue by Firedrake969** [OpenSprites/OpenSprites#25]
As per https://github.com/OpenSprites/OpenSprites/issues/24, we need consistency.

I generally name my stuff like this:
CSS/HTML classes/ids:  var-name
JS:  varName
PHP/SQL:  var_name

Also, for strings:
CSS/HTML:  single quotes
JS:  single quotes
PHP/SQL:  Double quotes

Thoughts?

**Comment by GrannyCookies** [comment]
For the naming, I'm the same.
For strings I use single for everything but CSS/HTML.

**Comment by bleush38p** [comment]
Personally, I've always used double quotes in HTML - I have no idea about HTML5, but I read somewhere many years ago that single quotes while supported by all browsers were never actually in the spec. (I have no idea if that's true or not, just my personal preference and a thing I read on the internet, so take it with at least four pounds of salt)

I found [this reference](http://www.scriptingok.com/tutorial/Single-quotes-vs-double-quotes-in-PHP) on ' vs " in PHP

> **PHP takes longer to process double-quoted strings.** Since the PHP parser has to read the whole string in advance to detect any variable inside—and concatenate it—it takes longer to process than a single quoted string. 

Double-quoted strings do text interpolation, so if we have strings that don't need it it seems best to use single quotes. Of course, when we want interpolation, double quotes are our friends. (Naturally, remembering proper escaping and handling to prevent XSS and SQLi.)

> **Single quotes are easier on the server.** Since PHP does not need to read the whole string in advance, the server can work faster and happier.

I agree with single quotes in JS - although, it's worth noting that I've found it far more likely that I'll need to escape an apostrophe in a string (`'Don\'t press that button!'`) than the times that I use double quotes in single-quote strings. (`'"who ever has to do this?" -me'`)

Do you think we should switch to double quotes when we have a string with an apostrophe, or should we escape the apostrophe?

**Comment by GrannyCookies** [comment]
Escape the apostrophe.
