### ISSUE TITLE
Clean up the css

### ISSUE THREAD

**Issue by Firedrake969** [OpenSprites/OpenSprites#27]
the navbar css file should actually contain navbar css, and stuff like that, rather than in one big CSS file.

**Comment by GrannyCookies** [comment]
agreed

**Comment by Firedrake969** [comment]
please don't change anything yet though

**Comment by GrannyCookies** [comment]
I won't :P

**Comment by Firedrake969** [comment]
btw, login button on live site looks pretty until you click now - progress :D

**Comment by Firedrake969** [comment]
btw, what time zone are you in?

**Comment by Firedrake969** [comment]
From now until about 4:00 MST, it's fine for you guys to rearrange the styling and make it more organized - I have to go soon so we won't be committing over each other.

**Comment by GrannyCookies** [comment]
Woah.

**Comment by GrannyCookies** [comment]
I'm in GMT.

**Comment by andrewjcole** [comment]
Uhhh bump?
