### ISSUE TITLE
REMINDER: You can now remove the .php extension from URLs!

### ISSUE THREAD

**Issue by GrannyCookies** [OpenSprites/OpenSprites#28]
For example, http://opensprites.x10.mx/live/alpha/register.php is able to load at http://opensprites.x10.mx/live/alpha/register.

It won't get rid of the .php though, you'll need to do that.

**Comment by The-Cheese-Eater** [comment]
For some reason the main-css isn't being exercised onto the register page.

**Comment by GrannyCookies** [comment]
Yeah, I know. I've fixed it.

**Comment by The-Cheese-Eater** [comment]
Great! I'm loving that new logo, by the way. Is there a way we can make it more 'interactive', like a glow around it like Scratch's logo? Or will that require an 'animation' sequence triggered with XXX:hover?

**Comment by GrannyCookies** [comment]
A glowy effect? Okay.
By the way, I'm currently working on the user pages- see http://opensprites.x10.mx/live/alpha/users/?username=bob

**Comment by The-Cheese-Eater** [comment]
Nice work so far!

**Comment by GrannyCookies** [comment]
I'm pretty much done now, and throughout this week ('till next Monday) I will be on holiday w/out internet. http://opensprites.x10.mx/live/alpha/users/?username=GrannyCookies

**Comment by Firedrake969** [comment]
Awesome, I'll do backend with it and fix some scrolling stuff (like the word collections being visible in front of the username banner thing)

**Comment by GrannyCookies** [comment]
@Firedrake969 I don't have the scrolling bug- heh, it's weird. And yes, do the backend, if any.

**Comment by Firedrake969** [comment]
http://prntscr.com/65g5o5

**Comment by GrannyCookies** [comment]
That's delibrate :P It's semi-transparent.

**Comment by Firedrake969** [comment]
Ah, ok.  Maybe we should use JS to make the bar squeeze up when you scroll down a certain amount, and have it be in front of everything?

**Comment by GrannyCookies** [comment]
Ooh, yes, good idea!

**Comment by GrannyCookies** [comment]
I've added a 404 error page when the code cannot find the user on Scratch (i.e. does not exist). I've also made it find the username with proper capitalisation from the Scratch server, see http://opensprites.x10.mx/live/alpha/users/?username=GrIffPatch

**Comment by Firedrake969** [comment]
awesome, am making it also so the user must be registered to see their page

**Comment by GrannyCookies** [comment]
Ok. I need to go now, so bye! (Make the login/register work :P)

**Comment by Firedrake969** [comment]
yessir xD

**Comment by liam4** [comment]
Uh, couldn't you just put the register at /register/index.php? Then you can have all the register-related scripts inside of /register, right?
