### ISSUE TITLE
Where do we want the "box" and "box-content" classes?

### ISSUE THREAD

**Issue by Rumanti** [OpenSprites/OpenSprites#29]
From what I understand, the 'box' and 'box-content' puts the content plus heading in scratch-like div-boxes. Where are these kind of boxes going to be used? When should the content use or not use these classes? I'm confused.

**Comment by andrewjcole** [comment]
It is used on the home page at the moment. In Scratch, it's kind of used to divide sections. Like to keep the comments section on a project page separate from the Studios section.

**Comment by Firedrake969** [comment]
seems resolved.
