### ISSUE TITLE
user page banner when scrolling down

### ISSUE THREAD

**Issue by Firedrake969** [OpenSprites/OpenSprites#32]
It should:
1.  Minimize (so get shorter)
2.  Be in front of everything else (no matter what)

**Comment by bleush38p** [comment]
Suggestion: CSS for two different classes (.navbar, .navbar.smaller) with transitions then use jQuery to add or remove the class on scrollup or scrolldown / when scrolled to the top.

**Comment by andrewjcole** [comment]
I'll see if I can do anything about it. Might not be until tomorrow.

**Comment by andrewjcole** [comment]
Hmmm... I'm having some troubles. I guess whoever gets to it first.

**Comment by Firedrake969** [comment]
ok

**Comment by andrewjcole** [comment]
Are we keeping it still or making it scroll with the rest of the page? I'm still figuring out how to test locally on Linux.

**Comment by Firedrake969** [comment]
Make it scroll, and change the z-index of the user's banner to be in front of everything.

**Comment by andrewjcole** [comment]
Okay. Might be able to get it done tomorrow, as school's already been cancelled because of so much snow.

**Comment by Firedrake969** [comment]
Ok, thanks.

**Comment by zappy1333** [comment]
I tried to fix this, I changed the z-index, I also added a "user since" section

**Comment by andrewjcole** [comment]
I don't think I can do the animation. I don't have enough JS experience.

**Comment by GrannyCookies** [comment]
@andrewjcole You can use css transitions, but I can do the JS if you do the CSS?
@Firedrake969 Something is VERY wrong with the userpage, it's not even loading anymore!

**Comment by Firedrake969** [comment]
Nothing's wrong - it shouldn't load if the user isn't registered.

**Comment by GrannyCookies** [comment]
@Firedrake969 I changed it so it would allow any user for now, until you get registering working.

**Comment by Firedrake969** [comment]
Just leave it, please... makes it easier for everyone to get a semi-working version ready.

**Comment by GrannyCookies** [comment]
@Firedrake969 Sorry. But OK.
