### ISSUE TITLE
.htaccess rewriting

### ISSUE THREAD

**Issue by Firedrake969** [OpenSprites/OpenSprites#34]
.htaccess features we should add:

- turn /users/?username=username into /users/username (simple .htaccess rewrite, I believe)

Will be updated as we get deeper into development.

**Comment by Firedrake969** [comment]
ongoing but not done.  Reopening.

**Comment by andrewjcole** [comment]
http://stackoverflow.com/questions/13003319/htaccess-rewrite-query-string-as-path

**Comment by Firedrake969** [comment]
go ahead and do it if you want - I won't be doing so until I figure out exactly what's needed

**Comment by andrewjcole** [comment]
I'm not to experienced with doing stuff with htaccess. I could try, I guess.

**Comment by GrannyCookies** [comment]
I will.

**Comment by GrannyCookies** [comment]
Done. http://dev.opensprites.x10.mx/users/grannycookies
