### ISSUE TITLE
Email Notifications?

### ISSUE THREAD

**Issue by andrewjcole** [OpenSprites/OpenSprites#35]
Later on, think we'll do email notifications? Like for if someone follows you? (If that idea doesn't fall through)

**Comment by The-Cheese-Eater** [comment]
I don't think you should get an email if someone follows you, but perhaps one if someone you follow has uploaded something? Email account confirmation would be needed too.

**Comment by jayforsythe** [comment]
I don't think it should notify you via email if something happens on your account. People would not like this if they're following tons of people.

**Comment by The-Cheese-Eater** [comment]
Yeah, that is a good point.

**Comment by andrewjcole** [comment]
What about an option to turn on or off the feature?
It would also be neat to do an Android app that sends notifications to your device, but that's way in the future. :P

**Comment by The-Cheese-Eater** [comment]
The option to toggle it is good. I like that app idea. :green_apple:



(Remember ScratchyApp...)

**Comment by Firedrake969** [comment]
First, let's finish this thing completely :P

Sure, toggleable, but make it so it's off by default.

**Comment by The-Cheese-Eater** [comment]
Yeah, we don't want to force people to sign up with disposable emails. :P :lock:

**Comment by Firedrake969** [comment]
Resolved?

**Comment by andrewjcole** [comment]
I guess we can decide this later. We're not going to be adding this for awhile.

**Comment by Firedrake969** [comment]
Yup.
