### ISSUE TITLE
Creating a Github Job

### ISSUE THREAD

**Issue by The-QullzToxic** [OpenSprites/OpenSprites#36]
If it is possible (I've seen it, but not actually used it) wouldn't it be good to use a github job to upload to the site every hour or somthing?

**Comment by The-Cheese-Eater** [comment]
Nice idea, but what if someone pushed a faulty script or we had a troll incident? Having auto uploading would be basically like handing FTP credentials to everyone. :P

**Comment by Firedrake969** [comment]
yay you used my labels :D

**Comment by Firedrake969** [comment]
yay you used my labels again xD
It'd be nice, but I agree with @The-Cheese-Eater

**Comment by The-Cheese-Eater** [comment]
lol I didn't know you could even add labels. :P :package: :horse: :cow2:

**Comment by The-QullzToxic** [comment]
Guess so, we don't want a troll :package: cause :watch: will be wasted fixing the site :3

**Comment by andrewjcole** [comment]
He could get hacked and we'd have to :hand: them and throw them in the :toilet: . That's all I got xD

**Comment by DM5555** [comment]
I agree with quillz, we do not want :trollface:

**Comment by The-QullzToxic** [comment]
Would making the auto upload go to another :file_folder: so those :trollface: get thrown down the :toilet: so :-1: for the :trollface:

**Comment by DM5555** [comment]
?

**Comment by andrewjcole** [comment]
This is getting rather :o2: fftopic .

**Comment by Firedrake969** [comment]
...

Closing until we can show we can actually focus.

**Comment by andrewjcole** [comment]
I think we've decided no. Too risky.

**Comment by Firedrake969** [comment]
Ok.
