### ISSUE TITLE
OpenSprites Logo text

### ISSUE THREAD

**Issue by andrewjcole** [OpenSprites/OpenSprites#37]
The OpenSprites logo is like so:
```
<span class="logo-name">
    <b>OPEN</b>SPRITES
</span>
```
I know in some concept illustrations, we had the "OPEN" part bolded (<-- that's not a word :P). This bold tag isn't doing anything. Are we going to keep it bolded? If not, the `<b>` tag isn't needed.

**Comment by Rumanti** [comment]
If it means anything, I don't know it. I do think the bold thing made the logo looks better (kinda easier to read :P) but I prefer this syntax. (because the bold thing is for style?)
HTML:
```
<span class="logo-name">
    <span id="some-id">OPEN</span>SPRITES
</span>
```
CSS:
```
#some-id {
    font-weight:bold(or any number);
}
```
Also because the ```font-weight``` CSS selector is more customizable.

**Comment by andrewjcole** [comment]
@Rumanti True, but what I mean is that you can't even see the bold. Instead of <OPEN>SPRITES, it shows up as OPENSPRITES.

**Comment by Rumanti** [comment]
Oh, sorry. I thought you meant "are we going to keep this bold-thing style?".

**Comment by andrewjcole** [comment]
I think it might be something with the font. Can someone smarter than me give some input? :stuck_out_tongue:
