### ISSUE TITLE
IRC Channel

### ISSUE THREAD

**Issue by The-QullzToxic** [OpenSprites/OpenSprites#38]
Hi, I made a IRC Channel cause I can :p 
It`s on the freenode network on the channel #OpenSprites 

https://freenode.net/irc_servers.shtml

**Comment by liam4** [comment]
Just curious, what's an IRC Channel? :P I have no idea.

It looks like the link is some sort of chat boxy type thing? I have no idea.

**Comment by pilppe** [comment]
Many developers use IRC channels for chatting together. Also they are as old as me.

**Comment by The-Cheese-Eater** [comment]
Internet Relay Channels. I found a page on them on books explaining Windows 95-98.

**Comment by andrewjcole** [comment]
OpenSprites: Made in US and elsewhere. xD

**Comment by The-QullzToxic** [comment]
We need somthing like irc, so we can chat without clogging up other things.

**Comment by Firedrake969** [comment]
Nah, just use issues - I doubt any of us are on at around the same time (Except @GrannyCookies and I xD)

**Comment by The-Cheese-Eater** [comment]
I sometimes catch you an GrannyCookies pushing updates. :P I was honestly under the impression that you lived in the UK until now. :P

**Comment by andrewjcole** [comment]
I'm GMT-4:00 timezone. :p

**Comment by pilppe** [comment]
GMT 2+ here ;)

**Comment by The-Cheese-Eater** [comment]
I think only about three or four of the developers (including me) actually are on GMT. :P

**Comment by Firedrake969** [comment]
Mst here and about to start school

**Comment by The-Cheese-Eater** [comment]
Wow, it's morning where you are! :O It's 3:00 here! :P

**Comment by liam4** [comment]
It's 11:00 here, and obviously I'm on when you are now. :P

**Comment by The-Cheese-Eater** [comment]
I think this just proves my point about incompatible time zones. xD

**Comment by liam4** [comment]
:+1:

**Comment by zappy1333** [comment]
I'm in GMT as well

**Comment by Firedrake969** [comment]
IRC wouldn't work based on time incompatibility, it seems

**Comment by The-Cheese-Eater** [comment]
We are actually all in IRC atm

**Comment by Firedrake969** [comment]
I'm in school xD

**Comment by andrewjcole** [comment]
School was cancelled for me >:)

**Comment by Firedrake969** [comment]
Lucky....

**Comment by The-QullzToxic** [comment]
Y U CLOSE MEH IRC TOPIC WHEN I SICK :3

**Comment by The-Cheese-Eater** [comment]
Because we don't need to discuss it anymore, and it clutters issues and makes us off-topic. That's why. :P

**Comment by DM5555** [comment]
Do we even need irc any more?

**Comment by The-Cheese-Eater** [comment]
We can use it sometimes.

**Comment by andrewjcole** [comment]
I'm usually on, as well as pilippe, DM5555 and liam showed up today.

**Comment by The-Cheese-Eater** [comment]
and me :P

**Comment by DM5555** [comment]
And quillz
