### ISSUE TITLE
Node.js vs PHP

### ISSUE THREAD

**Issue by Firedrake969** [OpenSprites/OpenSprites#4]
Which one?  Or both?

**Comment by andrewjcole** [comment]
I personally only know PHP and I've never actually used Node.js in a project before.

**Comment by The-Cheese-Eater** [comment]
I think we should use PHP, since that's the language that most of the collaborators know.

**Comment by 109C** [comment]
Both isn't really an option, as PHP and Node don't work together. I think we should use PHP.

**Comment by The-Cheese-Eater** [comment]
@109C What is your username on Scratch? I was under the impression you were Liam48D

**Comment by 109C** [comment]
@The-Cheese-Eater My screen name on Scratch is 109Celsius, since 109C would have been too short.

**Comment by The-Cheese-Eater** [comment]
@109C Ok, thanks.

**Comment by Firedrake969** [comment]
I vote PHP also, and it seems like we've reached a consensus, so closing.
