### ISSUE TITLE
A more legible font for the main container

### ISSUE THREAD

**Issue by jayforsythe** [OpenSprites/OpenSprites#41]
The font in use is fine for the navbar, but for the body it looks kind of thin and light. Perhaps we could use a more bold font?

**Comment by pilppe** [comment]
Why dont you fork the code and do a pull request?

**Comment by Firedrake969** [comment]
No need to fork - just add it and describe it in your commit, and we'll revert it if need be.

**Comment by zappy1333** [comment]
I think it looks OK

**Comment by andrewjcole** [comment]
Soooo... no change?

**Comment by The-Cheese-Eater** [comment]
I think it's ok, but I'll look into alternative fonts too.
