### ISSUE TITLE
Password Encryption

### ISSUE THREAD

**Issue by pilppe** [OpenSprites/OpenSprites#43]
When user registers to the page, what encryption are you guys gonna use to provide maximum safety? SHA512? Because im not gonna register to a page that encrypts password with MD5 or SHA1 :-1: 
or even worse, plaintext
This is how i did my login password encryption (which is MD5, but that was when i was inexperienced :smile:)
```PHP
// username and pw sent from the form
$myusername=$_POST['myusername']; 
$mypassword=$_POST['mypassword']; 

// encrypt password 
$encrypted_mypassword=md5($mypassword);
$sql="SELECT * FROM $tbl_name WHERE username='$myusername' and password='$encrypted_mypassword'";
$result=mysql_query($sql);

**Comment by The-QullzToxic** [comment]
I guess we`ll use sha512 if we get ssl, or strange will find somthing better as he is a security freak, No offence.

**Comment by Firedrake969** [comment]
PHP's password_verify function (more secure to cracking than sha512, AFAIK)
