### ISSUE TITLE
Logo could use anti-aliasing

### ISSUE THREAD

**Issue by andrewjcole** [OpenSprites/OpenSprites#44]
Is it just me, or does the 
![os logo](https://cloud.githubusercontent.com/assets/10202163/6240341/82bb33d6-b6e3-11e4-98ba-fed8dd1cc970.png) in the logo look like it could use some anti-aliasing? It looks kind of like it was made in MS paint right now. Probably because it was shrunk down.

**Comment by Firedrake969** [comment]
agreed

**Comment by pilppe** [comment]
I tried anti-aliasing but literally the only way to fix this is ask the creator to make a new picture since he is the one with the original .psd

**Comment by pilppe** [comment]
Okay, i added my own mockups! Check them out please, they are not shrunk down so they should look good.

**Comment by The-Cheese-Eater** [comment]
Those mockups you have there look pretty cool! Could you make a slightly larger version in black so I can see it better? :P Thanks.

**Comment by pilppe** [comment]
Of course, im happy that you like them :smiley:

**Comment by pilppe** [comment]
Its there now.

**Comment by The-Cheese-Eater** [comment]
righto

**Comment by pilppe** [comment]
The picture is small, but basicly its just OpenSprites with a font Ubuntu Condensed with an open folder

**Comment by The-Cheese-Eater** [comment]
Ok. Where do you think the logo should sit?

**Comment by pilppe** [comment]
In the same spot the logo we have atm is

**Comment by The-Cheese-Eater** [comment]
Righto, lets see what the rest of the team thinks.

**Comment by andrewjcole** [comment]
Is it on the live preview yet?

**Comment by The-Cheese-Eater** [comment]
Not yet, since it's in the graphics and mockups directory which doesn't get pushed to the live preview.

**Comment by andrewjcole** [comment]
Ah ok
