### ISSUE TITLE
Userpages bring 404?

### ISSUE THREAD

**Issue by andrewjcole** [OpenSprites/OpenSprites#45]
User pages seem to be broken in the latest live alpha update. Feel free to close if this has been fixed since. 
http://opensprites.x10.mx/live/alpha/users/?username=andrewjcole

**Comment by Firedrake969** [comment]
No, that's on purpose.

**Comment by andrewjcole** [comment]
Okay. Makes sense. Still am working out testing locally.

**Comment by Firedrake969** [comment]
ok

**Comment by andrewjcole** [comment]
Yay! Got it working!
