### ISSUE TITLE
tipgiver.js and other stuff

### ISSUE THREAD

**Issue by pilppe** [OpenSprites/OpenSprites#46]
So now, first off.

I dont know if this script was just a waste of time or overall stupid. 
But i think we have to try this.
We can add unlimited amounts of random tips show everytime the user reloads the page. It can be anything. 

But the thing is, what does everyone else think off this? It would be awesome actually adding some great tips that are somehow connected to Scratch, Scratch scripting or Scratch spriting. It would be pretty awesome.

Now the second one im building is just a concept, and the file only exists in my own fork of OpenSprites.

Its a countdown script for things like "305 days, 18 hours, 46 minutes and 18 seconds till Christmas" <-- Thats just an example. I dont want to put it to our upstream GitHub yet but it exists in my own fork.

So if you guys dont like these, tell me on the chat. YES I understand that we still need to make so many things and im maybe adding too much stupid stuff, but Scratch userbase consists off 6-16 year old kids, and they like these simple things (snowing, countdown and tip givers for example are pretty cool for kids) and it can really improve our sites future.

Countdown.js (in my fork)
https://github.com/pilppe/OpenSprites/commit/e15ec1ce922ef117673dc250d0e287d30da51c0b
Tipgiver.js (in OpenSprites main repo)
https://github.com/OpenSprites/OpenSprites/commit/c036f0f74667e9fde72594dd234aebe24de88b10

**Comment by andrewjcole** [comment]
Sounds pretty neat!

**Comment by The-Cheese-Eater** [comment]
I like that idea! If the tips we include are appropriate to the site, then I think that would be a great feature! Example: "Remember to cap off your script with the 'End Script' block!". Perhaps there could be a way of users submitting their own tips in the future? :P

**Comment by Firedrake969** [comment]
Tipgiver?  No preference, though could get annoying

Countdown seems pointless imo and distracts from the main point of the site

**Comment by pilppe** [comment]
I dont see how tipgiver could get annoying :/ but i can understand countdown

**Comment by Firedrake969** [comment]
Where or when would the tip giver pop up?

**Comment by pilppe** [comment]
Its for everyone to decide, i was thinking of right top

**Comment by The-Cheese-Eater** [comment]
How about it stays as a static sentence at the bottom of the page or footer? The footer is already full, however.

**Comment by pilppe** [comment]
Bottom of the page sounds wayy better

**Comment by The-Cheese-Eater** [comment]
righto then, is that agreed?

**Comment by andrewjcole** [comment]
I like it.

**Comment by Firedrake969** [comment]
Sure

**Comment by zappy1333** [comment]
I like the idea- maybe just on the homepage though, not every page.

**Comment by pilppe** [comment]
It could be a scrolling text too

**Comment by Rumanti** [comment]
I support putting 'tipgiver' at the bottom of the page. Sounds good for those who don't want to be annoyed. If someone wants a tip, they can scroll down. Refresh if they want a new tip.

**Comment by The-Cheese-Eater** [comment]
Yeah, I agree with @Rumanti here.

**Comment by liam4** [comment]
I like this idea, I think we should add it for sure. Maybe a PHP list so that it's a surprise what can come up (rather than JS, where you can just inspect-element the script and you'll get the whole array).

**Comment by The-Cheese-Eater** [comment]
Yeah, a PHP list would be better imo. And people can't inspect element the PHP and pretend to hack. :P

**Comment by liam4** [comment]
Right, that's what I figured. Want me to start making a script for it?

**Comment by pilppe** [comment]
You cant inspect element if its in an external file?

**Comment by liam4** [comment]
Nope, PHP just can't be inspect-element-ed. But JavaScripts can so that's why we should use PHP.

**Comment by pilppe** [comment]
If the external file is located in, lets say header.php and index.php has an include for header.php how is it possible to inspect element an external javascript file?

**Comment by pilppe** [comment]
We can obfuscate the javascript on the site too if its so important that nobody sees our tips? Lol

**Comment by liam4** [comment]
Hmm - that would probably work. Besides that when people go to header.php, they can then read the script through inspect element.

The only way we could make it not have a "hackable" tip giver would be to put the code directly in `<?php ... ?>` (as in, have a function called `tipgiver` or something).

And nope, there's people who have web browsers that have prettify in it. :P

**Comment by The-QullzToxic** [comment]
Make it look like that pin it button

**Comment by zappy1333** [comment]
I have made a PHP version of the tipgiver and put them both in a "tipgiver" file.

**Comment by pilppe** [comment]
We can say its closed.
