### ISSUE TITLE
Blog feature?

### ISSUE THREAD

**Issue by andrewjcole** [OpenSprites/OpenSprites#47]
I don't know about you guys, but I think it would be pretty neat to have a blog feature on the site. Kind of like to give updates to the users and to highlight useful scripts every week. 

Thoughts?

**Comment by pilppe** [comment]
Amazing, the same as on Scratch's webpage?

**Comment by The-Cheese-Eater** [comment]
Cool idea! Would we use a third party engine, or a home-made? :house_with_garden: The third party blogger will certainly be easier and save time, I can get it up and running in about half an hour. Vote?

**Comment by pilppe** [comment]
Third party engine would be pretty damn cool

**Comment by Firedrake969** [comment]
Keep it clean.  
I have no preference as low nv as it doesn't mess up stuff I'm working on

**Comment by Firedrake969** [comment]
Oops

**Comment by The-Cheese-Eater** [comment]
Righto, what blogger software would you recommend? I'm wary of using WordPress because I'm not too keen on a watermark.

**Comment by liam4** [comment]
Plain old HTML pages? ;) Why not hand code it? =P

**Comment by The-Cheese-Eater** [comment]
It's easier to use blogger software because it's a mini CMS designed for the task. I'd like to hand code it, but it's a bit of a pain to edit the same file all the time. I like the idea of a plain simple page, however.

**Comment by liam4** [comment]
True, plus coding in the comments might be a bit tough. :P My site runs on Wordpress but I prefer hand coding it, lots of pages are hand-coded. ;)

**Comment by The-Cheese-Eater** [comment]
I'm not sure comments are entirely essential. Anyhow, you've planted a seed in my brian, so I'll make the blog a really simple page but content rich.

**Comment by andrewjcole** [comment]
Just wait. I'm working on something. Not telling what it is yet ;)

**Comment by The-Cheese-Eater** [comment]
I'm slightly annoyed that someone moved the blog directory into the site directory. It's going to be hosted on a subdomain. :/

**Comment by andrewjcole** [comment]
blog.opensprites.x10.mx?

**Comment by The-Cheese-Eater** [comment]
Sorry, that was my mistake too. I've ended up making a conflict between mine and pilppe's commits, so I've had to revert it back. Could you please re-add your updates @pilppe. Sorry!

**Comment by pilppe** [comment]
I certainly understand, i always git pull before i push so no conflicts like that happen:smile:

**Comment by pilppe** [comment]
Oops

**Comment by The-Cheese-Eater** [comment]
Yeah, sorry! I thought about doing that, but I didn't think the changes were to the blog. :P

**Comment by pilppe** [comment]
Ok, now fixed.

I'd love that everyone would understand how important it is optimizing code and how important it is doing this:

```HTML
<link href='http://fonts.googleapis.com/css?family=Josefin+Sans:600|Arimo|Raleway|Noto+Sans' rel='stylesheet' type='text/css'>

instead of this

<link href='http://fonts.googleapis.com/css?family=Josefin+Sans:600' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Noto+Sans' rel='stylesheet' type='text/css'>

This is not that big of an mistake, but it makes the code look way better!

**Comment by andrewjcole** [comment]
I'm making my own design. (That I started on yesterday :P)

**Comment by The-Cheese-Eater** [comment]
Thanks again pilppe. :P 
@andrewjcole, shall I work on my design, and you work on yours, and then the rest of the team votes and we use the one most voted for?Sorry that I went about making another blog, I went a bit ahead of myself. :P

**Comment by andrewjcole** [comment]
Sounds fine to me. :) Here's my (not really) live progress: http://ajcscratch.x10.mx/osblog/

**Comment by liam4** [comment]
Mine's going great, all I need is to get the editor going and a few notes here and there and I'll have a complete blogging tool, customizable as anything. =3

**Comment by The-Cheese-Eater** [comment]
Great!

**Comment by andrewjcole** [comment]
Liam's sounds like the best for functionality!

**Comment by liam4** [comment]
Thanks, the editor is currently being finished up. :)
