### ISSUE TITLE
Please - connect to IRC everytime you want to do something!

### ISSUE THREAD

**Issue by pilppe** [OpenSprites/OpenSprites#49]
Hello!

Everytime we are making something and we are not updating our files actively, someone can do an commit and it mixes things up and its hard to revert everything back.

We need to get everyone to join the IRC chat @The-QullzToxic  created a while ago. Its really important and we can keep track on whats everyone doing.

Even though theres nobody online, stay there! I'm usually online 12 hours a day on the IRC and i would love for someone else to talk there :sweat_smile: 
https://webchat.freenode.net/ Username: Your GitHub name and connect to #OpenSprites

**Comment by Firedrake969** [comment]
I'd rather not use the chat and use issues instead - more trackable

**Comment by DM5555** [comment]
But still, there are  people online on github, but not online on IRC, I want to do something but there is no one there

**Comment by Firedrake969** [comment]
^exactly

**Comment by The-Cheese-Eater** [comment]
fixed! :D http://dev.opensprites.x10.mx/

**Comment by Firedrake969** [comment]
Not completely- hit login and the pop up is messed up

**Comment by The-Cheese-Eater** [comment]
The popup is fine, it works for me. :P Registration links need to be fixed though. I meant to post this on #60

**Comment by DM5555** [comment]
I want to discuss about the upload proscess with someone on the IRC

**Comment by Firedrake969** [comment]
First login and registration have to be finished though

**Comment by Firedrake969** [comment]
Also, irc isn't that practical to track stuff - closing
