### ISSUE TITLE
Way to do PHP includes?

### ISSUE THREAD

**Issue by andrewjcole** [OpenSprites/OpenSprites#51]
include vs file_get_contents?

**Comment by Firedrake969** [comment]
include, because file_get_contents does NOT EXECUTE PHP FILES!

**Comment by andrewjcole** [comment]
Okay got it.

**Comment by andrewjcole** [comment]
Oops

**Comment by Firedrake969** [comment]
lol

**Comment by andrewjcole** [comment]
I guess this can be closed.

**Comment by Firedrake969** [comment]
Yup, as long as @pilppe doesn't keep using file_get_contents...
