### ISSUE TITLE
Scratchblocks integration

### ISSUE THREAD

**Issue by andrewjcole** [OpenSprites/OpenSprites#52]
Sorry for all the "issues" but here's another idea:

What about scratchblocks previews? Was this already planned?

**Comment by pilppe** [comment]
We could ask permission from ST and take their Scratchblocks :smile:

**Comment by The-Cheese-Eater** [comment]
I think somebody called blob(numbers) developed ScratchBlocks.

**Comment by The-Cheese-Eater** [comment]
The code is open source right here on GitHub: https://github.com/blob8108/scratchblocks2 It's under an Mit license, so we are free to use it how we wish as long as the license is respected and included with every copy.

**Comment by andrewjcole** [comment]
:) http://blob8108.github.io/scratchblocks2/#when%20green%20flag%20clicked%0Amove%20(10)%20steps%0Asay%20%5BHere's%20a%20working%20demonstration%5D

So anyway, any ideas on how to implement it?

**Comment by The-Cheese-Eater** [comment]
I've forked it into our org to tinker with it: https://github.com/OpenSprites/scratchblocks2
We could use it to render the uploaded scripts into the webpage so we won't need images?

**Comment by andrewjcole** [comment]
That's what I was thinking, yeah.

**Comment by The-Cheese-Eater** [comment]
The sprite images don't seem to load correct @ my end

**Comment by andrewjcole** [comment]
Only some do for me.

**Comment by bleush38p** [comment]
I'm already implementing scratchblocks in my thing that pulls resources from Scratch projects, [as I suggested earlier.](http://scratch.mit.edu/discuss/post/778414/)
