### ISSUE TITLE
Locally Testing on Linux

### ISSUE THREAD

**Issue by andrewjcole** [OpenSprites/OpenSprites#53]
How can I locally test OS on Linux?

I can already test PHP itself from var/www using http://localhost. But whenever I import the OS repo, I get blank. Nothing. White. I also have to change permissions on everything, but even then, I still get blank.

Help?

**Comment by The-Cheese-Eater** [comment]
Could you tell us some system info? Linux distro, etc? Is it just a simple HTTP server or did you get LAMP? (Linux, Apache, MySQL, PHP) Can you access it from another PC on `pcname.lan`?

**Comment by andrewjcole** [comment]
I'm using Elementary OS Luna
All I did was this: aboutlinux.eu/how-to-run-php-on-ubuntu/

**Comment by The-Cheese-Eater** [comment]
Looks like they are having issues with their own servers, because according to my computer: "Firefox can't find the server at www.aboutlinux.eu.". :P

**Comment by pilppe** [comment]
Why do you have to change permissions? On Ubuntu 14.10 i dont and i tested Xubuntu 14.10 too

**Comment by andrewjcole** [comment]
Yep. I had to change permissions on everything and still blank screen for everything.

**Comment by liam4** [comment]
I dunno, on OS X Mavericks and above, I can use the `php` command (that's what I've been using for testing my blog) but I don't know how to run it on Linux - perhaps a similar command?

**Comment by The-Cheese-Eater** [comment]
I'm having a Linux machine arriving soon, so I can test it then.

**Comment by The-QullzToxic** [comment]
@The-Cheese-Eater is that a Pi2? :3

**Comment by The-Cheese-Eater** [comment]
Nope, it's an old Fujitsu Siemens laptop. I got it yesterday, but it has less RAM than described on Ebay, so I may have to buy some more before I install a fully functional OS. It currently has OpenDOS on it.

**Comment by pilppe** [comment]
Install Lubuntu on it, it uses LXDE and its very lightweight (even more lightweight than XFCE)

And yeah, to fix this issue i did this: (use LAMP because WAMP sucks)
sudo apt-get install tasksel
sudo tasksel install lamp-server
after that go check out localhost.

if you want to edit /var/www/index.php etc. type this in your terminal:
sudo chown -R yourusername /var/www/ that makes you an owner
sudo chmod -R 755 /var/www/ now apache can edit it etc.

Good luck!

**Comment by andrewjcole** [comment]
Will try when I have the chance! Many thanks!

**Comment by pilppe** [comment]
Updated my comment, both cheese and andrew should check it.

**Comment by The-Cheese-Eater** [comment]
Thanks, there good advice! When I first checked the BIOs, it said there was 200+MB of RAM installed, when the listing was 500MB. >:( The laptop is for taking outside where I may get dirt in this one, so it's not crucial to have loads of power.

**Comment by The-QullzToxic** [comment]
Ah, the times you wish they did laptop skins xD

**Comment by pilppe** [comment]
What do you mean?

**Comment by andrewjcole** [comment]
I still didn't get to try this out yet, but I did find my Windows Vista notebook, so I can try on that if this doesn't work.

**Comment by The-Cheese-Eater** [comment]
Ok, let us know.
