### ISSUE TITLE
Remove permanant snow :P

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#54]
It's all EdenStudio's fault, he set up the JS snow, but didn't get the timer set up. jk :P I think the snow is making the footer play up somehow.

**Comment by Firedrake969** [comment]
remove it until it's fixed, imo

**Comment by pilppe** [comment]
Just remove it for a while

**Comment by The-Cheese-Eater** [comment]
Righto then

**Comment by pilppe** [comment]
Added script that only enables it when its Christmas day.
