### ISSUE TITLE
Top menu bar improvement?

### ISSUE THREAD

**Issue by liam4** [OpenSprites/OpenSprites#55]
A couple ideas for the menu bar. When you resize the window to be really small, a few buttons end up appearing "below" the menu bar, just as lines that fill in a background when you hover over them. Basically it would have a different style for those when the screen is smaller, e.g. maybe when the mouse hovers over a little button they go left, and when the mouse is out it goes right?

By the way, this would be achieved via using `:hover` in the CSS stylesheet and `@media`:

```css
@media all and (max-width: 660px;) {
   /* This is where code for the smaller nav bar would go. */
}

@media all and (min-width: 661px;) {
    /* This is where code for the larger (normal) nav bar would go. */
}

/* Then normal styling below. */
```

Note that you can combine `min-width` and `max-width` inside of the `all and (`...`)` part of the line.

```css
@media all and (min-width: 666px; max-width: 666px;) {
    * {
        background-color: red;
        color: blue;
    }
}
```

And one last thing that I think would be really handy for styling:

```css
@media handheld and (max-width: [insert width of iPhone here]) {
    /* iPhone styling here */
}

@media handheld and (min-width: [insert width of iPhone + 1 here]) {
    /* iPhone+ (i.e., iPad) styling here */
}
```

That's all fairly easy to understand, right? ;)

_(Note - I've added high priority because Scratch not having a real iPad site (besides the [mobile forums](http://scratch.mit.edu/discuss/m/)) is really sad and stops me from using it to check notifications on mobiles/handhelds.)_
_(Note2 - woot, super formatted epic post. :D)_

**Comment by andrewjcole** [comment]
That actually sounds good. The lack of responsiveness or at least mobile version on the Scratch site sickens me. :P

I've actually been going for a kind of responsive look myself here: http://ajcscratch.x10.mx/osblog/

**Comment by liam4** [comment]
Saw your site, it looks like a nice design. :) Note the [official OS blog](http://blog.opensprites.x10.mx) though. ;) (I did see that it seems to be a personal blog though, so just your posts there? :P)

**Comment by andrewjcole** [comment]
Second last post https://github.com/OpenSprites/OpenSprites/issues/47 :P
