### ISSUE TITLE
Bug Reporter (and Feature Suggester) in organization groups?

### ISSUE THREAD

**Issue by liam4** [OpenSprites/OpenSprites#62]
I was thinking that there should be a **Bug Reporter** group, and possibly a **Feature Suggester** group as well, but maybe merge that with **Bug Reporter**. 

Is it possible for me to join two groups at once?

**Comment by The-Cheese-Eater** [comment]
Can we not just report bugs when we come across them though? :P

**Comment by pilppe** [comment]
We dont really need those groups to be honest, we just need extra hands and if we come to an issue we can report them ourselves

**Comment by Firedrake969** [comment]
Everyone reports bugs :P
