### ISSUE TITLE
Translation of the site?

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#63]
ScratchBlocks2 supports translation since it gets the translations from the Scratch translation server. Perhaps we could implement translation at a much later stage to open the site to non-english speakers? I know we have some multilingual speakers in the development team, so that could be a bonus for translation?

**Comment by liam4** [comment]
Those are quite the labels lol.

Yeah, I think this would be a good idea. But don't count on me translating it to anything but Python (as in, the programming language). ;)

**Comment by The-Cheese-Eater** [comment]
:P I think the only thing that would need translating would be pages written by us. User generated content would stay in English unless there was an alternative, however the ScratchBlocks2 engine we will use for previewing uploaded scripts supports translation.

**Comment by Rumanti** [comment]
:+1: I don't know what to say..

**Comment by The-Cheese-Eater** [comment]
Huh? @Rumanti

**Comment by pilppe** [comment]
Haha, i can translate to Finnish easily

**Comment by The-Cheese-Eater** [comment]
That would be cool!

**Comment by liam4** [comment]
Agreed.

**Comment by Rumanti** [comment]
@The-Cheese-Eater I meant to say that it's a good idea but I don't have any other thing to say.

**Comment by The-Cheese-Eater** [comment]
Ahh I see

**Comment by andrewjcole** [comment]
Je peut le traduire en Français.

**Comment by Firedrake969** [comment]
Ich kann ein bischen Deutsch sprechen.

**Comment by The-Cheese-Eater** [comment]
Great! You won't have much translation work really, just translating privacy and license policies, and important pages.

**Comment by liam4** [comment]
```python
import random
print "How's this %s?" % ["going", "doing", "happening"][random.randrange(1, 3)]```

Like I said, the only language I can do is Python and I doubt we need a Python version of the site. But I'll keep watch on this thread. :P

**Comment by pilppe** [comment]
@liam4 u srs? we talking bout languages

**Comment by liam4** [comment]
@pilppe No. The only other language I know is a tiny bit of Latin and French. :P

**Comment by The-Cheese-Eater** [comment]
We could have a Latin OpenSprites? :P

**Comment by liam4** [comment]
I was doing a Latin tutorial, like, five years ago. That's the last time I used Latin. So, while we could, don't expect me to make it. ;)

**Comment by The-Cheese-Eater** [comment]
:P I'm not sure how many average Scratchers know Latin anyhow. :P

**Comment by pilppe** [comment]
Latin is a dead language, please no

**Comment by The-QullzToxic** [comment]
No no, Translate into latin :3

**Comment by DM5555** [comment]
Nobody speaks latin as their first language

**Comment by Firedrake969** [comment]
xD

**Comment by Rumanti** [comment]
Jadi, kita jadi menerjemahkan, tidak? (so, are we going to translate?)

**Comment by Firedrake969** [comment]
Not yet - it's very low priority.

**Comment by Rumanti** [comment]
@Firedrake969 Whoops, wrong word. Replace the "going" with "planning" and "jadi" with "akan". xD

**Comment by The-Cheese-Eater** [comment]
:P I'll close this until later on in development.
