### ISSUE TITLE
Host alpha on a subdomain

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#64]
This is DM's idea, I'm voicing it. We are allowed a few more subdomains on our domain. If we have alpha.opensprites.x10.mx, then that should solve some issues with file paths, and it will be neater than the current system. What does everyone say?

**Comment by DM5555** [comment]
This will also fix issue #60

**Comment by liam4** [comment]
This is important and needs to happen now, I just finished my blog but it'll only run locally and probably won't work on the [Site Alpha](http://opensprites.x10.mx] if you update it at the moment.

In other words, we need it. :3

**Comment by Firedrake969** [comment]
alpha.domain.com?

Agreed.

**Comment by The-Cheese-Eater** [comment]
Right, I'll go and make that domain now. Bear in mind that some things won't work properly until updated.

**Comment by The-Cheese-Eater** [comment]
http://dev.opensprites.x10.mx/

**Comment by liam4** [comment]
Lol, I'm watching the directory fill up. ;)

**Comment by liam4** [comment]
Are you adding in [http://dev.opensprites.x10.mx/Blog/liam4/index.php](http://dev.opensprites.x10.mx/Blog/liam4/index.php)?

**Comment by The-Cheese-Eater** [comment]
Woop, it works!

**Comment by The-Cheese-Eater** [comment]
You can get to your blog at: blog.opensprites.x10.mx/liam4

**Comment by liam4** [comment]
Oh, cool. But you'll have to install marked there.

**Comment by The-Cheese-Eater** [comment]
What do you mean?

**Comment by liam4** [comment]
Sorry, I should have linked it - [marked](https://github.com/chjj/marked), as in the JavaScript package. I use it because my posts are "formatted" in markdown. Just make sure marked is located in `/node_modules/marked`, and `marked.js` is at `/node_modules/marked/lib/marked.js`. :)

**Comment by pilppe** [comment]
dev.openspritex.x10.mx
