### ISSUE TITLE
Blog Design?

### ISSUE THREAD

**Issue by andrewjcole** [OpenSprites/OpenSprites#65]
From what I know, we have two blogs going. One that everyone else is doing and one I'm pretty much doing on my own. :P

Which one seems more fitting? I honestly won't mind if mine is rejected because I can just use it for something later anyway. 

http://opensprites.x10.mx/blog/andrewjcole/
http://blog.opensprites.x10.mx/

I guess this isn't really important now, but oh well...

**Comment by liam4** [comment]
We have three, it's just that [mine](http://dev.opensprites.x10.mx/Blog/liam4/index.php) is still in progress and hasn't been tested on the server (just locally).

**Comment by The-Cheese-Eater** [comment]
I vote andrewjcole's over the second one.

**Comment by DM5555** [comment]
I vote second one

**Comment by Firedrake969** [comment]
I vote first

**Comment by andrewjcole** [comment]
Can't wait to see Liam's blow us all away :P

**Comment by The-Cheese-Eater** [comment]
I must say the same there @andrewjcole

**Comment by liam4** [comment]
XD I still have to bug fix it, and the theme isn't great _yet_. :P

**Comment by The-QullzToxic** [comment]
Can I have a go :3

**Comment by Rumanti** [comment]
I vote for @andrewjcole 's blog.

**Comment by liam4** [comment]
I'm so sad everybody is voting for everybody else while I'm finishing up my spectacular blog that will:

<blockquote> andrewjcole wrote:
Can't wait to see Liam's blow us all away. :P
</blockquote>

:P

**Comment by Rumanti** [comment]
Well, blow our minds ASAP then. Waiting is hard. :angry: XD

**Comment by liam4** [comment]
I'm going, I'm going, I've been working on it all day these last couple days. XD
