### ISSUE TITLE
Don't check node_modules into git

### ISSUE THREAD

**Issue by bleush38p** [OpenSprites/OpenSprites#68]
Use a manifest instead and add `node_modules` to `.gitignore`
https://docs.npmjs.com/all#should-i-check-my-node_modules-folder-into-git

**Comment by bleush38p** [comment]
Fixed in 79c239c

**Comment by bleush38p** [comment]
Never mind. Not fixed.

**Comment by bleush38p** [comment]
*please don't close issues which haven't been resolved.*

**Comment by The-QullzToxic** [comment]
Issue has been resolved by pilppe.

**Comment by bleush38p** [comment]
The folder should be removed, too.
