### ISSUE TITLE
Navbar should be integrated with the titlebar

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [OpenSprites/OpenSprites#7]
It feels awkward to have a navbar on top and then a title bar below that. Let's put the navbar on the bottom of the titlebar (and remove the border-radius on the bottom of the titlebar - looks kinda bad)

**Comment by andrewjcole** [comment]
Or you could use the titlebar and when the page is scrolled down, a sticky nav bar appears?

**Comment by andrewjcole** [comment]
Or you could use the titlebar and when the page is scrolled down, a sticky nav bar appears?

**Comment by The-Cheese-Eater** [comment]
I like andrewjcole's idea. But then it means that the user has to scroll down the page before having access to other pages, which may become cumbersome. Having an ease of access navigation bar would be the best thing really, like what MegaApuTurkUltra said.

**Comment by The-QullzToxic** [comment]
I think @andrewjcole is saying that the nav bar IS the title bar, and when you scroll down the nav bar moves also.

**Comment by 109C** [comment]
@The-QullzToxic  So basically merging the title bar into the navbar ?

**Comment by The-Cheese-Eater** [comment]
I'd think so, @109C. Perhaps we just remove the entire title bar instead? It's a bit redundant and serves little purpose.

**Comment by The-QullzToxic** [comment]
![Like this](https://cloud.githubusercontent.com/assets/9355799/6004685/6d535692-aafc-11e4-9bc8-0df5183975a0.png)

**Comment by 109C** [comment]
Titlebar integrated with the navbar. Close?

**Comment by The-Cheese-Eater** [comment]
Pretty nice! I've just updated the live alpha version. http://opensprites.x10.mx/live/alpha/
