### ISSUE TITLE
Android App?

### ISSUE THREAD

**Issue by The-QullzToxic** [OpenSprites/OpenSprites#70]
I was wondering if we could have an app.

And yes I am bored and don`t have ideas for what to do.

**Comment by DM5555** [comment]
1. No
2. Same, I want to do some js at the moment

**Comment by The-QullzToxic** [comment]
Github has live updates... Anyway, I need ideas

**Comment by The-Cheese-Eater** [comment]
Interesting idea, but we don't even have a fully functional site yet!

(R.I.P ScratchyApp :P)

**Comment by The-QullzToxic** [comment]
Who says, That Scratchy App is dead https://www.youtube.com/watch?v=ns3M1Sj6x4o
