### ISSUE TITLE
Forum?

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#72]
A user forum for questions and suggestions? Third party software, of course.

**Comment by The-QullzToxic** [comment]
Sure, need me to set it up?

**Comment by The-Cheese-Eater** [comment]
Thanks, but it's best that I set it up because I have database and admin access.

**Comment by The-QullzToxic** [comment]
:3 Can I help set it up when it is set up xD

**Comment by The-Cheese-Eater** [comment]
I'm afraid only current admins shall get access because potentially sensible data could be placed in the wrong hands.

**Comment by DM5555** [comment]
You are very right to do so cheeseeater...

**Comment by andrewjcole** [comment]
Even OpenSource projects have to keep some stuff hidden. :P

**Comment by pilppe** [comment]
Open-source doesnt have the same files as the servers

**Comment by andrewjcole** [comment]
True

**Comment by The-Cheese-Eater** [comment]
We now have a forum! http://opensprites.x10.mx/forums/

**Comment by liam4** [comment]
Awesome! I was [first](http://opensprites.x10.mx/forums/?p=3-first). :3
