### ISSUE TITLE
NAVBAR STILL BROKEN

### ISSUE THREAD

**Issue by Firedrake969** [OpenSprites/OpenSprites#74]
Please fix ASAP.

**Comment by andrewjcole** [comment]
Really? It looks fine on http://dev.opensprites.x10.mx/

**Comment by Firedrake969** [comment]
Login popup seems broken

**Comment by The-Cheese-Eater** [comment]
It's not. :P If you mean that little arrow thing just below Login, that was there before.
![popuptest](https://cloud.githubusercontent.com/assets/9347154/6282855/6ccd4720-b8d3-11e4-803c-40faca9c88ea.gif)

**Comment by liam4** [comment]
Maybe if the sign up dialog was closer to the right, under the arrow?

**Comment by pilppe** [comment]
Yeah, the arrow looks broken.

**Comment by Firedrake969** [comment]
The arrow is broken - the login popular is too far left.

**Comment by Firedrake969** [comment]
Also, registration css is broken but I can fix that this weekend.

**Comment by Rumanti** [comment]
Fixed. See [this commit](https://github.com/OpenSprites/OpenSprites/commit/30c2df1fdfcae065dca634ca21f1f3c7c292c85a).

**Comment by pilppe** [comment]
^Yes i referenced it

**Comment by Firedrake969** [comment]
Your fix didn't work.

**Comment by andrewjcole** [comment]
The logo on the live site. :open_mouth:

**Comment by Rumanti** [comment]
@andrewjcole stupid me, I forgot to add background-size
@Firedrake969 It works for me. Is it still broken for you?

**Comment by Firedrake969** [comment]
still broken for me - now the login popup is in.

**Comment by Firedrake969** [comment]
Stop closing it until I verify.  Our design needs to accommodate for different screen sizes, remember that!  (laptop screen sizes, that is)  I'll see what I can do...

**Comment by Firedrake969** [comment]
Ok, fixed it - please don't try to revert to your change ( @pilppe ), because that was what broke it
