### ISSUE TITLE
Live preview update requests - Request updates here

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#76]
Please comment here if you need the live preview updated. I shall also comment if it is updated without request.

**Comment by The-Cheese-Eater** [comment]
Updated to latest commit. 344ce94f631cc3b566874a9287310124b45f1df0

**Comment by liam4** [comment]
I'd like to have the blog updated so that people can see my blog, but first I need to change one link in the sidebar.

**Comment by liam4** [comment]
Add **input wanted**? :P

**Comment by liam4** [comment]
@The-Cheese-Eater Added, could you please update the site now? :)

**Comment by The-Cheese-Eater** [comment]
Update request acknowledged. Updating blog...

**Comment by The-Cheese-Eater** [comment]
Blog updated as per @Liam4's request.

**Comment by liam4** [comment]
Does [it](http://blog.opensprites.x10.mx/liam4/index.php) look good? :D

**Comment by The-Cheese-Eater** [comment]
Very cool! Lets talk about this blog on the forums to keep this clean.

**Comment by zappy1333** [comment]
Can you add the about section to the site?

**Comment by pilppe** [comment]
Update site ^

**Comment by The-Cheese-Eater** [comment]
I can't at the moment, sorry. I'm tethering my laptop to my phone with a 250MB data limit. I can do it at approximately 6PM tonight.

**Comment by The-Cheese-Eater** [comment]
Live preview updated.

**Comment by Firedrake969** [comment]
awesome

**Comment by Firedrake969** [comment]
In the online file manager, is there a way to mass-upload/upload compressed files?

**Comment by The-Cheese-Eater** [comment]
Do you want to decompress on-server or leave it compressed? Can't you just upload files as normal? I use coreFTP instead of messing around with online FTP stuff.

**Comment by Firedrake969** [comment]
I've used a file manager on 000webhost before that allows you to upload .zip files and it decompresses it on-server.

**Comment by GrannyCookies** [comment]
@Firedrake969 How. Tell me.

**Comment by pilppe** [comment]
@GrannyCookies http://www.hostinger.com/ has the same feature too

**Comment by Firedrake969** [comment]
@GrannyCookies 
1.  Upload .zip
2.  Site opens it and uploads it as a set of files

That's how...

**Comment by The-Cheese-Eater** [comment]
Blog and site updated.

**Comment by Firedrake969** [comment]
On my iPhone, the login popup is broken - the box is weirdly left

**Comment by Firedrake969** [comment]
Lol, the register page is throwing so many errors since it's not done.

**Comment by GrannyCookies** [comment]
- From @Firedrake969, please DO NOT update the user page -

**Comment by Firedrake969** [comment]
Thanks, @GrannyCookies

**Comment by The-Cheese-Eater** [comment]
Righto

**Comment by Firedrake969** [comment]
Update all pages in /register, please.

**Comment by The-Cheese-Eater** [comment]
Done. :)

**Comment by GrannyCookies** [comment]
@Firedrake969 Is the register done? :D

**Comment by Firedrake969** [comment]
theoretically?  xD

**Comment by Firedrake969** [comment]
https://github.com/OpenSprites/OpenSprites/issues/85

**Comment by The-Cheese-Eater** [comment]
Acknowledged.

**Comment by GrannyCookies** [comment]
Updated main-style.css and upload folder.
See http://dev.opensprites.x10.mx/upload/

**Comment by GrannyCookies** [comment]
Please can you update main-style.css?

**Comment by The-Cheese-Eater** [comment]
Done! :)

**Comment by GrannyCookies** [comment]
Thanks.

**Comment by Firedrake969** [comment]
Better-ish
http://prntscr.com/6cs58e

**Comment by The-Cheese-Eater** [comment]
Can't we just shrink the pictures?

**Comment by GrannyCookies** [comment]
I think adding a margin to the footer on that page would work better

**Comment by The-Cheese-Eater** [comment]
Go ahead. :) @GrannyCookies

**Comment by GrannyCookies** [comment]
@The-Cheese-Eater can you approve my forum request?

**Comment by The-Cheese-Eater** [comment]
Done. :) I'm loving the new theme, btw!

**Comment by GrannyCookies** [comment]
@The-Cheese-Eater Thanks! I did it on the main site too :)

**Comment by The-Cheese-Eater** [comment]
@GrannyCookies Cool! It looks great!

**Comment by GrannyCookies** [comment]
Please update Site/assets/includes/connect.php and forums/themes/all.css.

**Comment by andrewjcole** [comment]
Could you update? I wanna test my welcome box.

**Comment by The-Cheese-Eater** [comment]
@andrewjcole I'll assign that to @GrannyCookies if he doesn't mind. I'm tethering my laptop to a phone at the moment. :stuck_out_tongue:

**Comment by The-Cheese-Eater** [comment]
I've now updated to the latest commit.

**Comment by andrewjcole** [comment]
Thanks! Should I change it for the dark site or is it fine?

**Comment by andrewjcole** [comment]
Update please?

**Comment by The-Cheese-Eater** [comment]
Done!

**Comment by andrewjcole** [comment]
Hmm... they still aren't changing for the dark theme for some reason.

**Comment by GrannyCookies** [comment]
@andrewjcole I'll look into it- I've been at a birthday party for the past 6 hours.

**Comment by GrannyCookies** [comment]
Fixed- it just wasn't updated on the server. Pure black looks... not amazing- changing to `brightness(70%);`  instead.

**Comment by GrannyCookies** [comment]
Scratch that (pun not intended)... I didn't see the colour change. Reverting.

**Comment by andrewjcole** [comment]
Sorry about how sloppy I did everything there. :anguished:

**Comment by GrannyCookies** [comment]
Heh, it was pretty good. I've added different coloured buttons based on your code- .btn is orange, .btn.red, .btn.blue, .btn.green, and .btn.yellow. Try 'em!

**Comment by andrewjcole** [comment]
Those are so awesome!

**Comment by GrannyCookies** [comment]
I've hardly tested them... welll actually, not at all, yet.
I'm doing the removal of "Login" and "Sign Up" when logged in now.

**Comment by andrewjcole** [comment]
You probably already knew everything here: http://esotalk.org/forum/456-simple-esotalk-login-integration/0

**Comment by GrannyCookies** [comment]
Yup. Only problem is, dev.opensprites is considered a different domain- so cookies are differentiated. So I have to edit the EsoTalk sourcecode.

**Comment by andrewjcole** [comment]
Oh, that makes it more of a pain.

**Comment by andrewjcole** [comment]
It probably would have been easier in the end to host it on the dev.opensprites subdomain.

**Comment by GrannyCookies** [comment]
It still is easier. But oh well.

**Comment by andrewjcole** [comment]
Good luck, soldier!

**Comment by GrannyCookies** [comment]
I did it on the x10 site- I've forgotten how...

**Comment by andrewjcole** [comment]
Does cheeseeater have an archive?

This issue is going offtopic. Maybe it would be better to discuss in Gitter?

**Comment by GrannyCookies** [comment]
Yeah.

**Comment by The-Cheese-Eater** [comment]
I believe you still have FTP access to the x10 site @GrannyCookies? I've got a full backup from the old host on my computer, but I can only upload it on Monday.

**Comment by GrannyCookies** [comment]
I do, yeah. I've fixed it now.

**Comment by The-Cheese-Eater** [comment]
Great. :)

**Comment by andrewjcole** [comment]
Please update when you have the chance.

**Comment by The-Cheese-Eater** [comment]
Doen

**Comment by MegaApuTurkUltra** [comment]
http://osdev.aputurk.tk updates automagically :P

**Comment by The-Cheese-Eater** [comment]
Yeah, so I guess we don't need this open any more. :P

**Comment by GrannyCookies** [comment]
I need the forums updating, please.

**Comment by GrannyCookies** [comment]
@MegaApuTurkUltra's thingy doesn't have the forums on it.

**Comment by MegaApuTurkUltra** [comment]
That's because the source isn't on the repo! What am I supposed to do?

**Comment by The-Cheese-Eater** [comment]
Forums updated ;)

**Comment by GrannyCookies** [comment]
> [**@MegaApuTurkUltra**](https://github.com/MegaApuTurkUltra):
> That's because the source isn't on the repo! What am I supposed to do?
Not add it- I was just stating why.

**Comment by The-Cheese-Eater** [comment]
We shouldn't need this now with MATU's OSdev. If you desperately need sometime on the site updating, email or comment on my profile. :P

**Comment by andrewjcole** [comment]
Except, like, for the login and register pages.

**Comment by The-Cheese-Eater** [comment]
Yeah
