### ISSUE TITLE
Logo looks ugly on the site

### ISSUE THREAD

**Issue by pilppe** [OpenSprites/OpenSprites#77]
I prefer the older one.

**Comment by The-Cheese-Eater** [comment]
How does it?

**Comment by Rumanti** [comment]
Cauzality had made it kindly for us. Why don't you tell Cauzality what's wrong with it so that s/he can fix it? Or made one on your own? I actually prefer images than logos. Sometimes annoying browsers display text horribly.

**Comment by pilppe** [comment]
Yes, but the logo looks horrible with the shine and all that..

**Comment by pilppe** [comment]
I did make 2 of my own

**Comment by Firedrake969** [comment]
That's an opinion, so I see no need to change it yet until we get more important stuff done

**Comment by pilppe** [comment]
Yeah, i wanted to remove the shine.

Did i say because i made my own you are gonna use it? No. Rumanti simply said that why not make my own

**Comment by Firedrake969** [comment]
"and i did make my own"

It seemed to imply something.

**Comment by GrannyCookies** [comment]
@pilppe I like the new one :/

**Comment by The-Cheese-Eater** [comment]
As do I. @GrannyCookies
