### ISSUE TITLE
We should host our own logo

### ISSUE THREAD

**Issue by andrewjcole** [OpenSprites/OpenSprites#78]
At the moment, the logo is hosted on http://score.mclub.us/os-logotype.svg

**Comment by Firedrake969** [comment]
Support

**Comment by The-Cheese-Eater** [comment]
Sorry for sounding dumb, but where is the actual link in our HTML for the logo? I can't seem find it anywhere. :P

**Comment by GrannyCookies** [comment]
@The-Cheese-Eater navbar.php.
Support, we can probably do it now without waiting for support though- it won't really make a difference.

**Comment by Rumanti** [comment]
@The-Cheese-Eater Actually it's in the CSS. :P at main-styles.css

**Comment by GrannyCookies** [comment]
Fixed.
