### ISSUE TITLE
Update to Site Notice #2

### ISSUE THREAD

**Issue by Firedrake969** [OpenSprites/OpenSprites#85]
DO NOT EVER update the connect.php in assets/includes.  I repeat - DO NOT EVER UPDATE IT TO THE SITE!

**Comment by GrannyCookies** [comment]
Um... why?

**Comment by Firedrake969** [comment]
Because it'll break the site's database connection.

**Comment by GrannyCookies** [comment]
Oh

**Comment by The-Cheese-Eater** [comment]
Righto then. Good job I haven't. :)

**Comment by The-QullzToxic** [comment]
is connect.php for local testing?

_Sent via Hubroid_

**Comment by Firedrake969** [comment]
No, and local testing soon won't really be possible.

**Comment by DM5555** [comment]
Calm Down

**Comment by Firedrake969** [comment]
I just want to make it clear so I don't spend too long figuring out what went wrong - it's happened before on my own projects xD
