### ISSUE TITLE
x10 Hosting 404s

### ISSUE THREAD

**Issue by Firedrake969** [OpenSprites/OpenSprites#86]
Pages randomly are deleted/brought back (as in they're not even there when I reupload a page and refresh) which makes it really hard to debug live.

**Comment by GrannyCookies** [comment]
Agreed, it's quite dodgey sometimes

**Comment by Firedrake969** [comment]
any idea how to fix?  It's getting kind of annoying to me.

**Comment by GrannyCookies** [comment]
You don't say, I've tried :(

**Comment by Firedrake969** [comment]
:(

**Comment by The-QullzToxic** [comment]
Switch or ask cheese to purge cloudflare, Included with x10 (How they offer so cheap services, they use someone else's...)

_Sent via Hubroid_

**Comment by andrewjcole** [comment]
x10hosting hasn't been to kind to me lately. It hasn't been updating even though I can see the changes in my CP and I get a blank error message when I try to create an FTP account.

**Comment by Firedrake969** [comment]
It's been updating, but it seems to think files aren't even there sometimes.

**Comment by The-QullzToxic** [comment]
It sounds like caching.

_Sent via Hubroid_

**Comment by The-Cheese-Eater** [comment]
Moved to Gwiddle and service has been resumed!
