### ISSUE TITLE
Purge the cloudflare cache on upload!

### ISSUE THREAD

**Issue by The-QullzToxic** [OpenSprites/OpenSprites#87]
_Sent via Hubroid_

**Comment by The-Cheese-Eater** [comment]
We don't use cloudflare?

**Comment by The-QullzToxic** [comment]
We do, x10 forces you do

_Sent via Hubroid_

**Comment by The-Cheese-Eater** [comment]
Where do they say that...?

**Comment by The-QullzToxic** [comment]
Go onto the cpanal (not their basic one, their advanced one) it says cloudflare

_Sent via Hubroid_

**Comment by The-Cheese-Eater** [comment]
How does one switch between?

**Comment by The-QullzToxic** [comment]
For their be a button in the corner

**Comment by Firedrake969** [comment]
What exactly does "for their be a button" mean?

**Comment by The-Cheese-Eater** [comment]
He's right, actually. Click 'Switch Theme' located in the right upper corner next to 'Logout'. Select CPanel. Personally I prefer Vesta CP over CPanel.

(Oh, the good old Gwiddle days...)

**Comment by The-Cheese-Eater** [comment]
And we do have cloudflare settings to tamper with, too! :)

**Comment by The-QullzToxic** [comment]
Its not that basic a web host XD

_Sent via Hubroid_

**Comment by The-Cheese-Eater** [comment]
Moved to Gwiddle and service has been resumed!
