### ISSUE TITLE
Upload layout broken under 980px 

### ISSUE THREAD

**Issue by bleush38p** [OpenSprites/OpenSprites#89]
On the upload page, sizing the window so it is less that 980px wide breaks the layout.

Semirelated: remove inline styling. In fact, I think getting rid of the `height: 900px;` from `.container.main` should fix this and other problems?

**Comment by andrewjcole** [comment]
Never use px. Use % or auto. Usually works best for most screens.

**Comment by bleush38p** [comment]
> Never use px. Use % or auto. Usually works best for most screens.

Hmm? I understand what you're saying, though not as much its relevance. I was simply stating the point where the page breaks - but yes, in general, use of px should be discouraged.

**Comment by GrannyCookies** [comment]
Resizing it on ANY page breaks the layout.

**Comment by GrannyCookies** [comment]
I'm going to also fix the navbar resizing- turn it into a sidebar when it doesn't fit on the screen.

**Comment by GrannyCookies** [comment]
Fixed! https://github.com/OpenSprites/OpenSprites/commit/74683255ceeffc0d4014c817029018cff3eb7479
