### ISSUE TITLE
An idea.

### ISSUE THREAD

**Issue by GrannyCookies** [OpenSprites/OpenSprites#90]
I have an idea- the forum registration/login works fine (and allows uploading of images to the server) - so why not add the Scratch comment checker thingy to that and then it will work perfectly, instead of the other registration on the main page (development is slow on it)? Also then people wouldn't need to sign up for the forums seperately.

What does everybody think?

**Comment by The-Cheese-Eater** [comment]
I'm not quire sure what you mean. Do you mean syncing the forum and main site login credentials?

**Comment by GrannyCookies** [comment]
Yes- using the forum for logging in and registering- then we don't have to worry about security as much as it has already been created by the guys at EsoTalk.

**Comment by GrannyCookies** [comment]
We also then can start with the upload process today if you approve this (I'm going to hunt around the EsoTalk code for the uploading of user profile images and see what I can scavenge) :P

**Comment by The-Cheese-Eater** [comment]
Go ahead and see what you can do! I'd ask firedrake though, because he made /register.

**Comment by GrannyCookies** [comment]
Yeah, I need to take a look. I'm thinking of adding scratchblocks to the forums too?

**Comment by GrannyCookies** [comment]
Slight problem- the forums is on a different domain to the dev site- which means no cookies.

**Comment by GrannyCookies** [comment]
@The-Cheese-Eater Okay, so I've built this little test:
http://dev.opensprites.x10.mx/tests/user.php will tell you YOUR details.
http://dev.opensprites.x10.mx/tests/user.php?userid=65 will tell you user 65's details. What do you think?

**Comment by The-Cheese-Eater** [comment]
Cool! For the link displaying my details, I get a complicated PHP error.

**Comment by GrannyCookies** [comment]
@The-Cheese-Eater You need to be logged into the forums for that to work.

**Comment by The-Cheese-Eater** [comment]
I think I may have been. :P

**Comment by GrannyCookies** [comment]
Hm.
