### ISSUE TITLE
== SITE CURRENTLY DOWN ==

### ISSUE THREAD

**Issue by GrannyCookies** [OpenSprites/OpenSprites#91]
OH FOR GOD'S SA- x10hosting's fault.

**Comment by The-Cheese-Eater** [comment]
Bah humbug. We should migrate to gwiddle.

**Comment by GrannyCookies** [comment]
ScratchExt is broken to ;(

**Comment by GrannyCookies** [comment]
YAY! It's fixed!

**Comment by The-Cheese-Eater** [comment]
woop! :D

**Comment by GrannyCookies** [comment]
:P

**Comment by GrannyCookies** [comment]
Currently down once again- 16/03/15

**Comment by liam4** [comment]
Down? ;-; Why would that be?

(On the other hand, this has reminded me to get ideas for Opensprites.. :P)

**Comment by The-Cheese-Eater** [comment]
It has been down for ages now, I think x10 may be blocking the forums somehow; maybe it breaches their ToS?

**Comment by GrannyCookies** [comment]
@The-Cheese-Eater Maybe...

**Comment by GrannyCookies** [comment]
Not sure how though.

**Comment by andrewjcole** [comment]
Grab everything and run. x10hosting is for the birds.

**Comment by liam4** [comment]
^

**Comment by The-Cheese-Eater** [comment]
:P

**Comment by GrannyCookies** [comment]
@The-Cheese-Eater Quick! :P

**Comment by andrewjcole** [comment]
I just thought I'd mention that Gwiddle support is awesome. I reported a problem and he fixed it and told me what was wrong right away. 

Keep away from x10hosting. Take your loved ones and run from this monster. There's still hope.
Have I been reading too much again?

**Comment by The-Cheese-Eater** [comment]
@andrewjcole :P I'm fed up of these big hosting companies making huge profits off the internet; it should be free and open to anyone. I'd happily host if I had the speed (upload speed of less then 1 MBPs :crying_cat_face:) and the security (I've checked my router settings, and I've seen loads of blocked intrusions! D:) I'm going to try and get the forums up and running on Gwiddle, and then we can see if the entire sit can be migrated without breaking too much. I'm going to connect up the DB tomorrow, it's getting late here.

**Comment by andrewjcole** [comment]
I'd rather support a Scratcher than a rich, greedy business man.

**Comment by The-QullzToxic** [comment]
But then the nice scratcher has grudges... Yay, I have to use the stupid buissness man. Thanks guy that will not be named! Your really nice to people...

**Comment by andrewjcole** [comment]
@The-QullzToxic I'm pretty sure we all know who you mean...

**Comment by The-Cheese-Eater** [comment]
I'm pretty sure I don't @andrewjcole. :P

**Comment by andrewjcole** [comment]
The owner of Gwiddle wouldn't let Quillz in.

**Comment by The-Cheese-Eater** [comment]
Ahh yes. ;P

**Comment by DM5555** [comment]
He would, he wants people to use his service after all

**Comment by DM5555** [comment]
even after the Scratchy/MeowMobile incident

**Comment by The-Cheese-Eater** [comment]
Moved to Gwiddle and service has been resumed!
