### ISSUE TITLE
Gitter... Replacing IRC xD

### ISSUE THREAD

**Issue by The-QullzToxic** [OpenSprites/OpenSprites#92]
I know this isn't important but we now have a gitter:
https://gitter.im/OpenSprites

**Comment by GrannyCookies** [comment]
Cool!

**Comment by MegaApuTurkUltra** [comment]
Pls no IRC lol. I still don't have an actual desktop client and freenode is 3hardtouse5me

**Comment by liam4** [comment]
This looks cool. :P
