### ISSUE TITLE
Migrate to gwiddle uk 

### ISSUE THREAD

**Issue by The-QullzToxic** [OpenSprites/OpenSprites#93]

**Comment by andrewjcole** [comment]
Isn't x10hosting unlimited, though? I'm not sure about Gwiddle.

**Comment by The-Cheese-Eater** [comment]
Gwiddle is hosted on Microsoft Azure, so it will be unlimited. We could ask ZeusKing19 if he could donate us a premium package for free, but I would feel a bit cheeky. At the moment I don't think there are any packages set up. A bonus of using Gwiddle is that we get more than 2 DBs, more subdomains, more than 2 FTP accounts, stats, and better control via (<3) VestaCP.

**Comment by The-Cheese-Eater** [comment]
Getting 503s on the forums D: I vote Gwiddle.

**Comment by GrannyCookies** [comment]
I guess Gwiddle is an idea. Migration time?

**Comment by The-Cheese-Eater** [comment]
I'm going to start copying files over now. :)

**Comment by andrewjcole** [comment]
You should consider getting a freenom domain or something, because dev.opensprites.gwiddle.co.uk seems a bit long to me.

**Comment by The-Cheese-Eater** [comment]
I have considered freenom stuff, but agghh, the domain and IP info you have to fill it just whacks me around the head! It never seems to work, no matter what I enter!

**Comment by Firedrake969** [comment]
Either way, I'd like the username/password for FTP so I can do live testing (When I get the time - school projects suddenly are becoming huge :P)

**Comment by The-Cheese-Eater** [comment]
I'm guessing you mean for Gwiddle?

**Comment by zeusking19** [comment]
Cheeky? Cheeky?! xD - You could have asked and been granted it anyway.

**Comment by The-QullzToxic** [comment]
I am farily experianced with DNS...

**Comment by The-Cheese-Eater** [comment]
That would be great @zeusking19 :D Thanks!

**Comment by The-Cheese-Eater** [comment]
Moved to Gwiddle and service has been resumed!

**Comment by The-QullzToxic** [comment]
:D
