### ISSUE TITLE
[close this issue after reading]

### ISSUE THREAD

**Issue by jayforsythe** [OpenSprites/OpenSprites#94]
I don't feel like I have anything to do on this, so I'm gonna leave. I'm tired of the notifications and don't know any PHP. Thanks for understanding.

**Comment by The-Cheese-Eater** [comment]
Ok. It's sad to see you leave, but I understand and respect your decision. :) We will be looking for beta testers soon. :) I only hope this doesn't trigger other people to leave. :/

**Comment by GrannyCookies** [comment]
@The-Cheese-Eater I ain't leaving- I've put too much time into this XD

**Comment by The-Cheese-Eater** [comment]
Phew! :P

**Comment by liam4** [comment]
@GrannyCookies Same, I just don't know what to work on lol.

**Comment by Firedrake969** [comment]
@GrannyCookies Same xD

**Comment by andrewjcole** [comment]
@Firedrake969 @GrannyCookies Same x3

**Comment by The-Cheese-Eater** [comment]
@andrewjcole Everyone is free to contribute what they can, when they feel like. :) Just having access to the experience and expertise of the team is a great bonus! Currently, I feel the current homepage is rather bland, empty and plain. I think we need to design the homepage a bit more and add more interactivity.

**Comment by GrannyCookies** [comment]
@The-Cheese-Eater I think we should move away from "Just Like Scratch"- for example the user page is very pretty (to me anyway) and we should go for a nicer design. Just thinking.

**Comment by GrannyCookies** [comment]
- Moved design disscussion over to #95 -
