### ISSUE TITLE
Disscussion: Design Ideas

### ISSUE THREAD

**Issue by GrannyCookies** [OpenSprites/OpenSprites#95]
**Dissuss design ideas for design below.**

> *@The-Cheese-Eater said:*
> Currently, I feel the current homepage is rather bland, empty and plain. I think we need to design the homepage a bit more and add more interactivity. Any ideas?

**Comment by GrannyCookies** [comment]
@The-Cheese-Eater I think we should move away from "Just Like Scratch"- for example the user page is very pretty (to me anyway) and we should go for a nicer design. Just thinking.

**Comment by andrewjcole** [comment]
Maybe like a tile design? Like this: 
![layout](https://cloud.githubusercontent.com/assets/10202163/6714324/6809bcca-cd76-11e4-93a2-9c5735033d74.png)

**Comment by GrannyCookies** [comment]
Yeah, that's what I was thinking- like... Windows Metro -esc?

**Comment by The-Cheese-Eater** [comment]
I agree @GrannyCookies, I like the user profiles at the moment. I think @andrewjcole's tile design would fit the bill, and it would fit in nicely with the clean look of the user profiles, too.

**Comment by GrannyCookies** [comment]
@The-Cheese-Eater Yeah. Should I work on it?

**Comment by liam4** [comment]
@GrannyCookies Looks like a nice design to me! :)

**Comment by GrannyCookies** [comment]
A quick search, and I found this: http://www.drewgreenwell.com/projects/metrojs

**Comment by The-Cheese-Eater** [comment]
That MetroJS stuff looks pretty cool! The only thing is, it looks quite a lot like what Microsoft have already done. :P

**Comment by bleush38p** [comment]
Yeah, I'm not a huge fan of the metrojs idea for OS. It looks neat, but I don't think it's right for us. As @The-Cheese-Eater said, it's been done, and even if we want something that looks similar we can code it ourselves, especially static tiles -- and I don't think we really need fancy flippy flashy slidey tiles, cool as they are.

**Comment by andrewjcole** [comment]
I think it could work, just keep them still. They don't need to move fancy. Besides, Microsoft didn't exactly invent the idea of fitting sections together like a puzzle.

**Comment by bleush38p** [comment]
They didn't invent it...but they sure as heck have claimed it. We don't
want to reek of any specific platform too much - that's why we're not using
Helvetia Neue, or Material Design, or Live® Tiles™. However, we certainly
can borrow the best aspects of each type of design language and incorporate
them into our own design.

**Comment by The-Cheese-Eater** [comment]
I agree with @bleush38p. A unique design would be best; tiles have been included in every Windows after 7. :P Take a look around where you are sitting. Are there any objects or inspiration that we could display information on, like the tiles? I most say though, tiles do seem a good option, it's a shame Microsoft coined them.

**Comment by GrannyCookies** [comment]
@The-Cheese-Eater TRIANGLESES!

**Comment by bleush38p** [comment]
YASS!!1 LET'S DO IT!

**Comment by andrewjcole** [comment]
YUS

**Comment by The-Cheese-Eater** [comment]
If we can fit what we need to fit in the triangles. :P

**Comment by andrewjcole** [comment]
It would be unique, that's for sure. But would it make sense in the end? :tongue:

**Comment by bleush38p** [comment]
Of course not. That's the fun. :P

**Comment by The-Cheese-Eater** [comment]
I think @andrewjcole is thinking up a design?
