### ISSUE TITLE
Change URLs to work with Gwiddle

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#96]
We need to change URLs from x10.mx to gwiddle.co.uk. Note that the developer sandbox is at dev.opensprites.gwiddle.co.uk now.

**Comment by GrannyCookies** [comment]
Maybe using / at the start is a good idea? Then we can use htaccess documentroot.

**Comment by The-Cheese-Eater** [comment]
Yeah, I suppose we'd have to re-write the URLs again once we move to the main site.

**Comment by GrannyCookies** [comment]
Hey, I've migrated the site-user-api to work with the new forums- http://dev.opensprites.gwiddle.co.uk/site-api/user.php?userid=1 = http://opensprites.gwiddle.co.uk/forums/?p=member/1-cheeseeater

**Comment by andrewjcole** [comment]
Forums aren't working any better for me...

**Comment by GrannyCookies** [comment]
You still can't login?

**Comment by pilppe** [comment]
I'm able to login
