### ISSUE TITLE
Put PHP comments in PHP blocks

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [OpenSprites/OpenSprites#98]
I did this for the 404 page here: https://github.com/OpenSprites/OpenSprites/commit/ffad3c85e038a80ea0a0e0505de43bbf8b409dcc

Basically, the issue is that we don't want hackers reading our comments
```php
<!-- Hey hackers, wassup, this following PHP code does X, Y, and Z -->
<?php
    Sample->text();
    echo "<p>content</p>";
?>
```
turns into
```php
<!-- Hey hackers, wassup, this following PHP code does X, Y, and Z -->
<p>content</p>
```
People can still read the comments! You all should be doing this instead:
```php
<?php /* This following PHP code does X, Y, and Z */
    Sample->text();
    echo "<p>content</p>";
?>
```
Which turns into
```php
<p>content</p>
```

**Comment by andrewjcole** [comment]
Yes! :D

**Comment by The-Cheese-Eater** [comment]
Yeah, that is a better idea. Can't they just look at the repo though? :P

**Comment by GrannyCookies** [comment]
^

**Comment by andrewjcole** [comment]
Still, it looks better when you click view source and you see a whole bunch of strange comments.

**Comment by GrannyCookies** [comment]
Yeah, it does.

**Comment by The-QullzToxic** [comment]
We can keep this TAPH SECWET :3

Or we can use our own private service....

**Comment by liam4** [comment]
I approve of putting the code inside of the PHP blocks, I think it looks neater.

**Comment by Rumanti** [comment]
Change all the HTML comments to inside comments? 
I've got no job. :(

**Comment by MegaApuTurkUltra** [comment]
Sure. Let's look professional if anyone happens to inspect element. Put all the comments in PHP.

Of course, one of the final things we do when we finish OpenSprites is compress all the html, css, and js, and try to compress images as JPEG. (Keep originals on the repo of course!) This will speed up page load times.

**Comment by GrannyCookies** [comment]
@MegaApuTurkUltra Yup.

**Comment by GrannyCookies** [comment]
@Rumanti CSS for the upload page?

**Comment by Rumanti** [comment]
@GrannyCookies ???

**Comment by GrannyCookies** [comment]
The /upload/?method=local has no styling
