### ISSUE TITLE
IMPORTANT: User page querystring changed

### ISSUE THREAD

**Issue by andrewjcole** [OpenSprites/OpenSprites#99]
I changed the querystring for user pages from username to id. For example:

This:
http://dev.opensprites.gwiddle.co.uk/users/?username=5

Is now this:
http://dev.opensprites.gwiddle.co.uk/users/?id=5

I will close this once everybody seems to know.

**Comment by The-Cheese-Eater** [comment]
Acknowledged.

**Comment by GrannyCookies** [comment]
Okay- I'm going to allow the page to have no querystring now too

**Comment by liam4** [comment]
Just saying, now I know. ;)

**Comment by GrannyCookies** [comment]
Use the normal syntax: /users/userid/
